<?php
require_once __DIR__.'/../config/session.php';require_once __DIR__.'/../config/auth.php';require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../config/helper.php';
check_access([1]);$db=Database::getInstance();
$guru_id=(int)($_GET['guru_id']??0);$semester=in_array($_GET['semester']??'',['Ganjil','Genap'],true)?$_GET['semester']:'';
$tahun=trim($_GET['tahun_ajaran']??'');$mulai=trim($_GET['tanggal_mulai']??'');$akhir=trim($_GET['tanggal_akhir']??'');
$valid_date=static fn($v)=>$v===''||(($d=DateTime::createFromFormat('Y-m-d',$v))&&$d->format('Y-m-d')===$v);
if(!$valid_date($mulai))$mulai='';if(!$valid_date($akhir))$akhir='';if($mulai&&$akhir&&$mulai>$akhir){$tmp=$mulai;$mulai=$akhir;$akhir=$tmp;}if(mb_strlen($tahun)>10)$tahun='';
$guru_list=$db->query('SELECT id,nama_lengkap FROM guru ORDER BY nama_lengkap')->fetchAll();$tahun_list=$db->query('SELECT DISTINCT tahun_ajaran FROM pengajaran ORDER BY tahun_ajaran DESC')->fetchAll(PDO::FETCH_COLUMN);

$ledger="SELECT p.guru_id,p.semester,p.tahun_ajaran,'materi' jenis,mat.created_at waktu,mat.judul judul,m.nama_mapel,k.nama_kelas FROM materi mat JOIN pengajaran p ON p.id=mat.pengajaran_id JOIN mapel m ON m.id=p.mapel_id JOIN kelas k ON k.id=p.kelas_id
UNION ALL SELECT p.guru_id,p.semester,p.tahun_ajaran,'tugas',t.created_at,t.judul,m.nama_mapel,k.nama_kelas FROM tugas t JOIN pengajaran p ON p.id=t.pengajaran_id JOIN mapel m ON m.id=p.mapel_id JOIN kelas k ON k.id=p.kelas_id
UNION ALL SELECT p.guru_id,p.semester,p.tahun_ajaran,'ujian',u.created_at,u.nama_ujian,m.nama_mapel,k.nama_kelas FROM ujian u JOIN pengajaran p ON p.id=u.pengajaran_id JOIN mapel m ON m.id=p.mapel_id JOIN kelas k ON k.id=p.kelas_id
UNION ALL SELECT p.guru_id,p.semester,p.tahun_ajaran,'absensi',sa.created_at,CONCAT('Pertemuan ',sa.pertemuan_ke),m.nama_mapel,k.nama_kelas FROM sesi_absensi sa JOIN pengajaran p ON p.id=sa.pengajaran_id JOIN mapel m ON m.id=p.mapel_id JOIN kelas k ON k.id=p.kelas_id
UNION ALL SELECT p.guru_id,p.semester,p.tahun_ajaran,'pengumpulan',pt.dikumpulkan_pada,t.judul,m.nama_mapel,k.nama_kelas FROM pengumpulan_tugas pt JOIN tugas t ON t.id=pt.tugas_id JOIN pengajaran p ON p.id=t.pengajaran_id JOIN mapel m ON m.id=p.mapel_id JOIN kelas k ON k.id=p.kelas_id
UNION ALL SELECT p.guru_id,p.semester,p.tahun_ajaran,'nilai_tugas',pt.dikumpulkan_pada,t.judul,m.nama_mapel,k.nama_kelas FROM pengumpulan_tugas pt JOIN tugas t ON t.id=pt.tugas_id JOIN pengajaran p ON p.id=t.pengajaran_id JOIN mapel m ON m.id=p.mapel_id JOIN kelas k ON k.id=p.kelas_id WHERE pt.nilai IS NOT NULL
UNION ALL SELECT p.guru_id,p.semester,p.tahun_ajaran,'esai_jawaban',COALESCE(su.waktu_selesai,su.waktu_mulai),u.nama_ujian,m.nama_mapel,k.nama_kelas FROM jawaban_siswa js JOIN soal_ujian so ON so.id=js.soal_id AND so.tipe_soal='ESAI' JOIN sesi_ujian su ON su.id=js.sesi_ujian_id JOIN ujian u ON u.id=su.ujian_id JOIN pengajaran p ON p.id=u.pengajaran_id JOIN mapel m ON m.id=p.mapel_id JOIN kelas k ON k.id=p.kelas_id WHERE js.jawaban_esai IS NOT NULL AND TRIM(js.jawaban_esai)<>''
UNION ALL SELECT p.guru_id,p.semester,p.tahun_ajaran,'nilai_esai',COALESCE(su.waktu_selesai,su.waktu_mulai),u.nama_ujian,m.nama_mapel,k.nama_kelas FROM jawaban_siswa js JOIN soal_ujian so ON so.id=js.soal_id AND so.tipe_soal='ESAI' JOIN sesi_ujian su ON su.id=js.sesi_ujian_id JOIN ujian u ON u.id=su.ujian_id JOIN pengajaran p ON p.id=u.pengajaran_id JOIN mapel m ON m.id=p.mapel_id JOIN kelas k ON k.id=p.kelas_id WHERE js.nilai_esai IS NOT NULL";
$event_where=[];$params=[];if($semester){$event_where[]='e.semester=?';$params[]=$semester;}if($tahun){$event_where[]='e.tahun_ajaran=?';$params[]=$tahun;}if($mulai){$event_where[]='e.waktu>=?';$params[]=$mulai.' 00:00:00';}if($akhir){$event_where[]='e.waktu<=?';$params[]=$akhir.' 23:59:59';}
$event_where_sql=$event_where?' WHERE '.implode(' AND ',$event_where):'';
$aggregate="SELECT e.guru_id,SUM(e.jenis='materi') materi,SUM(e.jenis='tugas') tugas,SUM(e.jenis='ujian') ujian,SUM(e.jenis='absensi') absensi,SUM(e.jenis='pengumpulan') pengumpulan,SUM(e.jenis='nilai_tugas') nilai_tugas,SUM(e.jenis='esai_jawaban') esai_jawaban,SUM(e.jenis='nilai_esai') nilai_esai FROM ($ledger) e $event_where_sql GROUP BY e.guru_id";
$sql="SELECT g.id,g.nip,g.nama_lengkap,COALESCE(a.materi,0) materi,COALESCE(a.tugas,0) tugas,COALESCE(a.ujian,0) ujian,COALESCE(a.absensi,0) absensi,COALESCE(a.pengumpulan,0) pengumpulan,COALESCE(a.nilai_tugas,0) nilai_tugas,COALESCE(a.esai_jawaban,0) esai_jawaban,COALESCE(a.nilai_esai,0) nilai_esai FROM guru g LEFT JOIN ($aggregate) a ON a.guru_id=g.id";
$outer_params=$params;if($guru_id){$sql.=' WHERE g.id=?';$outer_params[]=$guru_id;}$sql.=' ORDER BY g.nama_lengkap';
$stmt=$db->prepare($sql);$stmt->execute($outer_params);$laporan=$stmt->fetchAll();
foreach($laporan as &$r){$r['total_konten']=(int)$r['materi']+(int)$r['tugas']+(int)$r['ujian']+(int)$r['absensi'];$r['progres_tugas']=$r['pengumpulan']?((int)$r['nilai_tugas']/(int)$r['pengumpulan'])*100:0;$r['progres_esai']=$r['esai_jawaban']?((int)$r['nilai_esai']/(int)$r['esai_jawaban'])*100:0;}unset($r);

$detail_guru=null;$aktivitas_detail=[];
if($guru_id){foreach($laporan as $r)if((int)$r['id']===$guru_id)$detail_guru=$r;if($detail_guru){$dw=$event_where;$dp=$params;$dw[]='e.guru_id=?';$dp[]=$guru_id;$stmt=$db->prepare("SELECT e.* FROM ($ledger) e WHERE ".implode(' AND ',$dw)." AND e.jenis IN ('materi','tugas','ujian','absensi') ORDER BY e.waktu DESC LIMIT 100");$stmt->execute($dp);$aktivitas_detail=$stmt->fetchAll();}}

$format=$_GET['format']??'';
if(in_array($format,['excel','pdf'],true)){
 $judul='Laporan Produktivitas Guru';$periode=($mulai?:'Awal').' s.d. '.($akhir?:'Sekarang').' | '.($semester?:'Semua Semester').' | '.($tahun?:'Semua Tahun');
 $headers=['No','NIP','Guru','Materi','Tugas','Ulangan','Absensi','Total Aktivitas','Tugas Dinilai','Pengumpulan','Progres Tugas','Esai Dinilai','Jawaban Esai','Progres Esai'];$rows=[];foreach($laporan as $i=>$r)$rows[]=[$i+1,$r['nip']?:'-',$r['nama_lengkap'],$r['materi'],$r['tugas'],$r['ujian'],$r['absensi'],$r['total_konten'],$r['nilai_tugas'],$r['pengumpulan'],number_format($r['progres_tugas'],1,',','.').'%', $r['nilai_esai'],$r['esai_jawaban'],number_format($r['progres_esai'],1,',','.').'%'];
 $name='Aktivitas_Guru_'.date('Ymd');$esc=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
 if($format==='excel'){header('Content-Type: application/vnd.ms-excel; charset=UTF-8');header('Content-Disposition: attachment; filename="'.$name.'.xls"');header('Cache-Control: no-store');echo "\xEF\xBB\xBF".'<html><head><meta charset="UTF-8"><style>table{border-collapse:collapse}th,td{border:1px solid #64748b;padding:6px;white-space:nowrap}th{background:#dbeafe}</style></head><body><h2>'.$judul.'</h2><p>'.$esc($periode).'</p><table><tr>';foreach($headers as $h)echo '<th>'.$esc($h).'</th>';echo '</tr>';foreach($rows as $row){echo '<tr>';foreach($row as $c)echo '<td>'.$esc($c).'</td>';echo '</tr>';}echo '</table></body></html>';exit;}
 $pdfesc=static function($v){$v=iconv('UTF-8','Windows-1252//TRANSLIT//IGNORE',(string)$v);return str_replace(['\\','(',')',"\r","\n"],['\\\\','\\(','\\)',' ',' '],$v);};$lines=[$judul,$periode,str_repeat('-',145),implode(' | ',$headers),str_repeat('-',145)];foreach($rows as $row)foreach(str_split(implode(' | ',array_map('strval',$row)),145) as $part)$lines[]=$part;if(!$rows)$lines[]='Tidak ada data.';$pages=array_chunk($lines,48);$objects=[1=>'<< /Type /Catalog /Pages 2 0 R >>',3=>'<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>'];$kids=[];$next=4;foreach($pages as $page){$po=$next++;$so=$next++;$kids[]="$po 0 R";$cmd="BT /F1 7 Tf 24 570 Td 10 TL\n";foreach($page as $line)$cmd.='('.$pdfesc($line).") Tj T*\n";$cmd.='ET';$objects[$po]="<< /Type /Page /Parent 2 0 R /MediaBox [0 0 842 595] /Resources << /Font << /F1 3 0 R >> >> /Contents $so 0 R >>";$objects[$so]="<< /Length ".strlen($cmd)." >>\nstream\n$cmd\nendstream";}$objects[2]='<< /Type /Pages /Kids ['.implode(' ',$kids).'] /Count '.count($kids).' >>';ksort($objects);$pdf="%PDF-1.4\n";$off=[0];foreach($objects as $n=>$body){$off[$n]=strlen($pdf);$pdf.="$n 0 obj\n$body\nendobj\n";}$xref=strlen($pdf);$max=max(array_keys($objects));$pdf.="xref\n0 ".($max+1)."\n0000000000 65535 f \n";for($i=1;$i<=$max;$i++)$pdf.=sprintf('%010d 00000 n ',$off[$i])."\n";$pdf.="trailer\n<< /Size ".($max+1)." /Root 1 0 R >>\nstartxref\n$xref\n%%EOF";header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="'.$name.'.pdf"');header('Content-Length: '.strlen($pdf));header('Cache-Control: no-store');echo $pdf;exit;
}
$query_state=['guru_id'=>$guru_id,'semester'=>$semester,'tahun_ajaran'=>$tahun,'tanggal_mulai'=>$mulai,'tanggal_akhir'=>$akhir];
require_once __DIR__.'/../includes/header.php';require_once __DIR__.'/../includes/sidebar.php';
?>
<div id="page-content-wrapper" class="teacher-activity-page"><style>
.teacher-activity-page{background:#f7f9fc;min-width:0}.activity-content{max-width:1400px;margin:auto}.activity-hero{background:linear-gradient(135deg,#172554,#1d4ed8);color:#fff;border-radius:22px;padding:28px;box-shadow:0 18px 44px rgba(29,78,216,.17)}.activity-card{border:1px solid #e8edf5!important;border-radius:18px!important;box-shadow:0 8px 28px rgba(15,23,42,.045)!important}.activity-table th{white-space:nowrap;font-size:.73rem;text-transform:uppercase;color:#64748b}.activity-table td{font-size:.82rem;vertical-align:middle}.progress{height:7px}.timeline-item{display:flex;gap:12px;padding:13px 0;border-bottom:1px solid #edf1f6}.timeline-icon{width:38px;height:38px;display:grid;place-items:center;border-radius:11px;flex:0 0 38px}.detail-anchor{scroll-margin-top:15px}@media(max-width:767.98px){.activity-content{padding:14px!important}.activity-hero{padding:21px;border-radius:18px}}
</style><nav class="navbar top-navbar px-3 px-md-4 py-3"><div><h5 class="fw-bold mb-0"><i class="fa-solid fa-person-chalkboard text-primary me-2"></i>Detail Aktivitas Guru</h5><small class="text-muted">Laporan produktivitas dan progres penilaian</small></div></nav><main class="container-fluid activity-content p-3 p-md-4">
<section class="activity-hero mb-3"><div class="d-flex justify-content-between align-items-center"><div><small class="text-uppercase fw-semibold opacity-75">Produktivitas Pengajaran</small><h2 class="h4 fw-bold my-1">Aktivitas Seluruh Guru</h2><p class="mb-0 opacity-75">Data faktual materi, tugas, ulangan, absensi, dan penilaian.</p></div><i class="fa-solid fa-chart-pie fa-2x opacity-50"></i></div></section>
<section class="card activity-card mb-3"><div class="card-body p-3"><form method="get" class="row g-2 align-items-end"><div class="col-md-4"><label class="form-label small fw-semibold">Guru</label><select name="guru_id" class="form-select"><option value="0">Semua Guru</option><?php foreach($guru_list as $g): ?><option value="<?= (int)$g['id'] ?>" <?= $guru_id===(int)$g['id']?'selected':'' ?>><?= sanitize($g['nama_lengkap']) ?></option><?php endforeach ?></select></div><div class="col-6 col-md-2"><label class="form-label small fw-semibold">Semester</label><select name="semester" class="form-select"><option value="">Semua</option><option <?= $semester==='Ganjil'?'selected':'' ?>>Ganjil</option><option <?= $semester==='Genap'?'selected':'' ?>>Genap</option></select></div><div class="col-6 col-md-2"><label class="form-label small fw-semibold">Tahun Ajaran</label><select name="tahun_ajaran" class="form-select"><option value="">Semua</option><?php foreach($tahun_list as $r): ?><option value="<?= sanitize($r) ?>" <?= $tahun===$r?'selected':'' ?>><?= sanitize($r) ?></option><?php endforeach ?></select></div><div class="col-6 col-md-2"><label class="form-label small fw-semibold">Dari Tanggal</label><input type="date" name="tanggal_mulai" value="<?= sanitize($mulai) ?>" class="form-control"></div><div class="col-6 col-md-2"><label class="form-label small fw-semibold">Sampai Tanggal</label><input type="date" name="tanggal_akhir" value="<?= sanitize($akhir) ?>" class="form-control"></div><div class="col-12 d-flex gap-2"><button class="btn btn-primary flex-grow-1"><i class="fa-solid fa-filter me-1"></i>Tampilkan</button><a href="aktivitas_guru.php" class="btn btn-light border">Reset</a></div></form></div></section>
<?php if($detail_guru): ?><section id="detailAktivitas" class="card activity-card detail-anchor mb-3"><div class="card-body p-3 p-md-4"><div class="d-flex justify-content-between gap-2 mb-3"><div><h6 class="fw-bold mb-1"><?= sanitize($detail_guru['nama_lengkap']) ?></h6><small class="text-muted">NIP <?= sanitize($detail_guru['nip']?:'-') ?> · <?= count($aktivitas_detail) ?> aktivitas pembelajaran ditampilkan</small></div><a href="?<?= http_build_query(array_merge($query_state,['guru_id'=>0])) ?>" class="btn btn-sm btn-light border align-self-start">Tutup Detail</a></div><div class="row g-3"><div class="col-lg-5"><h6 class="small fw-bold text-uppercase text-muted">Progres Penilaian</h6><div class="mb-3"><div class="d-flex justify-content-between small mb-1"><span>Tugas dinilai</span><strong><?= (int)$detail_guru['nilai_tugas'] ?>/<?= (int)$detail_guru['pengumpulan'] ?> (<?= number_format($detail_guru['progres_tugas'],1,',','.') ?>%)</strong></div><div class="progress"><div class="progress-bar bg-success" style="width:<?= min(100,$detail_guru['progres_tugas']) ?>%"></div></div></div><div><div class="d-flex justify-content-between small mb-1"><span>Esai dinilai</span><strong><?= (int)$detail_guru['nilai_esai'] ?>/<?= (int)$detail_guru['esai_jawaban'] ?> (<?= number_format($detail_guru['progres_esai'],1,',','.') ?>%)</strong></div><div class="progress"><div class="progress-bar bg-info" style="width:<?= min(100,$detail_guru['progres_esai']) ?>%"></div></div></div></div><div class="col-lg-7"><h6 class="small fw-bold text-uppercase text-muted">Aktivitas Pembelajaran Terbaru</h6><?php $meta=['materi'=>['fa-book-open','primary','Materi'],'tugas'=>['fa-list-check','warning','Tugas'],'ujian'=>['fa-file-circle-question','info','Ulangan'],'absensi'=>['fa-user-check','success','Absensi']];foreach($aktivitas_detail as $a): [$icon,$warna,$label]=$meta[$a['jenis']]; ?><div class="timeline-item"><span class="timeline-icon bg-<?= $warna ?>-subtle text-<?= $warna ?>"><i class="fa-solid <?= $icon ?>"></i></span><div><strong class="small"><?= $label ?> · <?= sanitize($a['judul']) ?></strong><small class="text-muted d-block"><?= sanitize($a['nama_mapel']) ?> · <?= sanitize($a['nama_kelas']) ?> · <?= date('d/m/Y H:i',strtotime($a['waktu'])) ?></small></div></div><?php endforeach ?><?php if(!$aktivitas_detail): ?><p class="text-muted">Tidak ada aktivitas pada periode ini.</p><?php endif ?></div></div></div></section><?php endif ?>
<section class="card activity-card"><div class="card-body p-0"><div class="d-flex flex-wrap justify-content-between gap-2 px-3 px-md-4 py-3 border-bottom"><div><h6 class="fw-bold mb-0">Laporan Produktivitas</h6><small class="text-muted"><?= count($laporan) ?> guru ditampilkan</small></div><div class="d-flex gap-2"><a class="btn btn-sm btn-success" href="?<?= http_build_query(array_merge($query_state,['format'=>'excel'])) ?>"><i class="fa-solid fa-file-excel me-1"></i>Excel</a><a class="btn btn-sm btn-danger" href="?<?= http_build_query(array_merge($query_state,['format'=>'pdf'])) ?>"><i class="fa-solid fa-file-pdf me-1"></i>PDF</a></div></div><div class="table-responsive"><table class="table activity-table table-hover mb-0"><thead class="table-light"><tr><th class="ps-4">Guru</th><th>Materi</th><th>Tugas</th><th>Ulangan</th><th>Absensi</th><th>Total Aktivitas</th><th>Penilaian Tugas</th><th>Penilaian Esai</th><th>Aksi</th></tr></thead><tbody>
<?php foreach($laporan as $r): ?><tr><td class="ps-4"><strong><?= sanitize($r['nama_lengkap']) ?></strong><br><small class="text-muted">NIP <?= sanitize($r['nip']?:'-') ?></small></td><td><?= (int)$r['materi'] ?></td><td><?= (int)$r['tugas'] ?></td><td><?= (int)$r['ujian'] ?></td><td><?= (int)$r['absensi'] ?></td><td><strong class="text-primary"><?= (int)$r['total_konten'] ?></strong></td><td><strong><?= (int)$r['nilai_tugas'] ?>/<?= (int)$r['pengumpulan'] ?></strong><br><small><?= number_format($r['progres_tugas'],1,',','.') ?>%</small></td><td><strong><?= (int)$r['nilai_esai'] ?>/<?= (int)$r['esai_jawaban'] ?></strong><br><small><?= number_format($r['progres_esai'],1,',','.') ?>%</small></td><td><a href="?<?= http_build_query(array_merge($query_state,['guru_id'=>(int)$r['id']])) ?>#detailAktivitas" class="btn btn-sm btn-primary"><i class="fa-solid fa-eye me-1"></i>Detail</a></td></tr><?php endforeach ?><?php if(!$laporan): ?><tr><td colspan="9" class="text-center text-muted py-5">Tidak ada guru sesuai filter.</td></tr><?php endif ?></tbody></table></div><div class="alert alert-light border-0 border-top rounded-0 mb-0 small text-muted"><i class="fa-solid fa-circle-info me-1"></i>Karena sistem belum menyimpan waktu pemberian nilai, filter periode penilaian memakai waktu pengumpulan tugas dan waktu sesi ujian terkait.</div></div></section>
</main></div><?php require_once __DIR__.'/../includes/footer.php'; ?>
