<?php
require_once __DIR__.'/../config/session.php';require_once __DIR__.'/../config/auth.php';require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../config/helper.php';
check_access([1]);$db=Database::getInstance();
$success=$_SESSION['operasional_success']??'';$error=$_SESSION['operasional_error']??'';unset($_SESSION['operasional_success'],$_SESSION['operasional_error']);

if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!verify_csrf($_POST['csrf_token']??'')){$_SESSION['operasional_error']='Token keamanan tidak valid. Silakan muat ulang halaman.';redirect('kontrol_operasional.php');}
 $action=$_POST['action']??'';
 try{
  if($action==='tutup_sesi'){
   $sesi_id=(int)($_POST['sesi_id']??0);
   $stmt=$db->prepare("SELECT sa.id,sa.pertemuan_ke,sa.status,g.nama_lengkap nama_guru,m.nama_mapel,k.nama_kelas FROM sesi_absensi sa JOIN pengajaran p ON p.id=sa.pengajaran_id JOIN guru g ON g.id=p.guru_id JOIN mapel m ON m.id=p.mapel_id JOIN kelas k ON k.id=p.kelas_id WHERE sa.id=?");$stmt->execute([$sesi_id]);$target=$stmt->fetch();
   if(!$target||$target['status']!=='Dibuka')throw new RuntimeException('Sesi tidak ditemukan atau sudah ditutup.');
   if(!tutup_sesi_absensi($db,$sesi_id))throw new RuntimeException('Sesi sudah diproses oleh pengguna lain.');
   $log="[OPERASIONAL ADMIN] Menutup sesi absensi ID $sesi_id | {$target['nama_guru']} | {$target['nama_mapel']} | {$target['nama_kelas']} | Pertemuan {$target['pertemuan_ke']}";
   catat_log($_SESSION['user_id'],$log);$_SESSION['operasional_success']='Sesi absensi berhasil ditutup dan siswa yang belum check-in dicatat Alpa.';
  }elseif($action==='sinkron_sesi'){
   $sesi_id=(int)($_POST['sesi_id']??0);$db->beginTransaction();
   $stmt=$db->prepare("SELECT sa.id,sa.pertemuan_ke,p.kelas_id,g.nama_lengkap nama_guru,m.nama_mapel,k.nama_kelas FROM sesi_absensi sa JOIN pengajaran p ON p.id=sa.pengajaran_id JOIN guru g ON g.id=p.guru_id JOIN mapel m ON m.id=p.mapel_id JOIN kelas k ON k.id=p.kelas_id WHERE sa.id=? AND sa.status='Ditutup' FOR UPDATE");$stmt->execute([$sesi_id]);$target=$stmt->fetch();
   if(!$target)throw new RuntimeException('Sesi tertutup tidak ditemukan.');
   $stmt=$db->prepare("INSERT INTO detail_absensi(sesi_absensi_id,siswa_id,status,keterangan) SELECT ?,s.id,'Alpa','Disinkronkan oleh Admin karena belum tercatat' FROM siswa s WHERE s.kelas_id=? AND NOT EXISTS(SELECT 1 FROM detail_absensi da WHERE da.sesi_absensi_id=? AND da.siswa_id=s.id)");
   $stmt->execute([$sesi_id,$target['kelas_id'],$sesi_id]);$jumlah=$stmt->rowCount();$db->commit();
   catat_log($_SESSION['user_id'],"[OPERASIONAL ADMIN] Sinkronisasi sesi absensi ID $sesi_id | {$target['nama_guru']} | {$target['nama_mapel']} | {$target['nama_kelas']} | $jumlah siswa ditambahkan sebagai Alpa");
   $_SESSION['operasional_success']=$jumlah?"Sinkronisasi selesai. $jumlah siswa ditambahkan sebagai Alpa.":'Sesi sudah lengkap; tidak ada data yang perlu ditambahkan.';
  }elseif($action==='atur_akses'){
   $pengajaran_id=(int)($_POST['pengajaran_id']??0);$pertemuan=(int)($_POST['pertemuan_ke']??0);$status=$_POST['status']??'';
   if($pertemuan<1||$pertemuan>20||!in_array($status,['Dibuka','Dikunci'],true))throw new RuntimeException('Pertemuan atau status akses tidak valid.');
   $stmt=$db->prepare('SELECT p.id,g.nama_lengkap nama_guru,m.nama_mapel,k.nama_kelas FROM pengajaran p JOIN guru g ON g.id=p.guru_id JOIN mapel m ON m.id=p.mapel_id JOIN kelas k ON k.id=p.kelas_id WHERE p.id=?');$stmt->execute([$pengajaran_id]);$target=$stmt->fetch();if(!$target)throw new RuntimeException('Pengajaran tidak ditemukan.');
   $db->beginTransaction();$stmt=$db->prepare('SELECT status FROM akses_pertemuan WHERE pengajaran_id=? AND pertemuan_ke=? FOR UPDATE');$stmt->execute([$pengajaran_id,$pertemuan]);$status_lama=$stmt->fetchColumn()?:'Dikunci (default)';
   $stmt=$db->prepare("INSERT INTO akses_pertemuan(pengajaran_id,pertemuan_ke,status,dibuka_pada) VALUES(?,?,?,CASE WHEN ?='Dibuka' THEN NOW() ELSE NULL END) ON DUPLICATE KEY UPDATE status=VALUES(status),dibuka_pada=CASE WHEN VALUES(status)='Dibuka' THEN NOW() ELSE NULL END");$stmt->execute([$pengajaran_id,$pertemuan,$status,$status]);$db->commit();
   catat_log($_SESSION['user_id'],"[OPERASIONAL ADMIN] Akses pertemuan diubah $status_lama -> $status | {$target['nama_guru']} | {$target['nama_mapel']} | {$target['nama_kelas']} | Pertemuan $pertemuan");
   $_SESSION['operasional_success']="Akses pertemuan $pertemuan berhasil diubah menjadi $status.";
  }else throw new RuntimeException('Aksi operasional tidak dikenali.');
 }catch(Throwable $e){if($db->inTransaction())$db->rollBack();error_log('Kontrol operasional gagal: '.$e->getMessage());$_SESSION['operasional_error']=$e instanceof RuntimeException?$e->getMessage():'Tindakan operasional gagal diproses.';}
 redirect('kontrol_operasional.php');
}

$pengajaran=$db->query('SELECT p.id,p.semester,p.tahun_ajaran,g.nama_lengkap nama_guru,m.nama_mapel,k.nama_kelas FROM pengajaran p JOIN guru g ON g.id=p.guru_id JOIN mapel m ON m.id=p.mapel_id JOIN kelas k ON k.id=p.kelas_id ORDER BY g.nama_lengkap,k.nama_kelas,m.nama_mapel,p.tahun_ajaran DESC')->fetchAll();
$sesi_terbuka=$db->query("SELECT sa.id,sa.pertemuan_ke,sa.tanggal,sa.waktu_buka,sa.waktu_tutup,IF(sa.waktu_tutup<NOW(),1,0) kedaluwarsa,g.nama_lengkap nama_guru,m.nama_mapel,k.nama_kelas,(SELECT COUNT(*) FROM detail_absensi da WHERE da.sesi_absensi_id=sa.id) tercatat,(SELECT COUNT(*) FROM siswa s WHERE s.kelas_id=p.kelas_id) total_siswa FROM sesi_absensi sa JOIN pengajaran p ON p.id=sa.pengajaran_id JOIN guru g ON g.id=p.guru_id JOIN mapel m ON m.id=p.mapel_id JOIN kelas k ON k.id=p.kelas_id WHERE sa.status='Dibuka' ORDER BY kedaluwarsa DESC,sa.waktu_tutup")->fetchAll();
$sesi_tidak_lengkap=$db->query("SELECT sa.id,sa.pertemuan_ke,sa.tanggal,g.nama_lengkap nama_guru,m.nama_mapel,k.nama_kelas,(SELECT COUNT(*) FROM siswa s WHERE s.kelas_id=p.kelas_id) total_siswa,(SELECT COUNT(*) FROM detail_absensi da WHERE da.sesi_absensi_id=sa.id) tercatat FROM sesi_absensi sa JOIN pengajaran p ON p.id=sa.pengajaran_id JOIN guru g ON g.id=p.guru_id JOIN mapel m ON m.id=p.mapel_id JOIN kelas k ON k.id=p.kelas_id WHERE sa.status='Ditutup' AND EXISTS(SELECT 1 FROM siswa s WHERE s.kelas_id=p.kelas_id AND NOT EXISTS(SELECT 1 FROM detail_absensi da WHERE da.sesi_absensi_id=sa.id AND da.siswa_id=s.id)) ORDER BY sa.tanggal DESC LIMIT 50")->fetchAll();
$akses_terbuka=$db->query("SELECT ap.pengajaran_id,ap.pertemuan_ke,ap.dibuka_pada,g.nama_lengkap nama_guru,m.nama_mapel,k.nama_kelas FROM akses_pertemuan ap JOIN pengajaran p ON p.id=ap.pengajaran_id JOIN guru g ON g.id=p.guru_id JOIN mapel m ON m.id=p.mapel_id JOIN kelas k ON k.id=p.kelas_id WHERE ap.status='Dibuka' ORDER BY ap.dibuka_pada DESC,ap.id DESC")->fetchAll();
$stmt=$db->prepare("SELECT l.created_at,u.username,l.aktivitas,l.ip_address FROM log_aktivitas l LEFT JOIN users u ON u.id=l.user_id WHERE l.aktivitas LIKE '[OPERASIONAL ADMIN]%' ORDER BY l.created_at DESC,l.id DESC LIMIT 20");$stmt->execute();$audit_operasional=$stmt->fetchAll();
$kedaluwarsa=count(array_filter($sesi_terbuka,static fn($s)=>(int)$s['kedaluwarsa']===1));
require_once __DIR__.'/../includes/header.php';require_once __DIR__.'/../includes/sidebar.php';
?>
<div id="page-content-wrapper" class="ops-page"><style>
.ops-page{background:#f7f9fc;min-width:0}.ops-content{max-width:1400px;margin:auto}.ops-hero{background:linear-gradient(135deg,#7f1d1d,#dc2626);color:#fff;border-radius:22px;padding:28px;box-shadow:0 18px 44px rgba(220,38,38,.16)}.ops-card,.metric-card{border:1px solid #e8edf5!important;border-radius:18px!important;box-shadow:0 8px 28px rgba(15,23,42,.045)!important}.metric-icon{width:44px;height:44px;display:grid;place-items:center;border-radius:13px}.ops-table th{white-space:nowrap;font-size:.74rem;text-transform:uppercase;color:#64748b}.ops-table td{font-size:.82rem;vertical-align:middle}.audit-item{padding:12px 0;border-bottom:1px solid #edf1f6}.critical-row{background:#fff7ed}@media(max-width:767.98px){.ops-content{padding:14px!important}.ops-hero{padding:21px;border-radius:18px}}
</style><nav class="navbar top-navbar px-3 px-md-4 py-3"><div><h5 class="fw-bold mb-0"><i class="fa-solid fa-screwdriver-wrench text-danger me-2"></i>Kontrol Operasional Admin</h5><small class="text-muted">Penanganan sesi dan akses dengan audit log</small></div></nav><main class="container-fluid ops-content p-3 p-md-4">
<?php if($success): ?><div class="alert alert-success alert-dismissible fade show"><?= sanitize($success) ?><button class="btn-close" data-bs-dismiss="alert"></button></div><?php endif ?><?php if($error): ?><div class="alert alert-danger alert-dismissible fade show"><?= sanitize($error) ?><button class="btn-close" data-bs-dismiss="alert"></button></div><?php endif ?>
<section class="ops-hero mb-3"><div class="d-flex justify-content-between gap-3"><div><small class="text-uppercase fw-semibold opacity-75">Tindakan Terlindungi</small><h2 class="h4 fw-bold my-1">Pusat Penanganan Operasional</h2><p class="mb-0 opacity-75">Setiap perubahan dicatat dan dapat ditelusuri pada audit log.</p></div><i class="fa-solid fa-shield-halved fa-2x opacity-50"></i></div></section>
<div class="row g-2 mb-3"><?php foreach([['Sesi Terbuka',count($sesi_terbuka),'fa-door-open','primary'],['Sesi Kedaluwarsa',$kedaluwarsa,'fa-clock','danger'],['Data Tidak Lengkap',count($sesi_tidak_lengkap),'fa-triangle-exclamation','warning'],['Akses Terbuka',count($akses_terbuka),'fa-lock-open','success']] as [$label,$jumlah,$icon,$warna]): ?><div class="col-6 col-xl-3"><div class="card metric-card p-3"><div class="d-flex align-items-center gap-3"><span class="metric-icon bg-<?= $warna ?>-subtle text-<?= $warna ?>"><i class="fa-solid <?= $icon ?>"></i></span><div><small class="text-muted"><?= $label ?></small><h4 class="fw-bold mb-0"><?= $jumlah ?></h4></div></div></div></div><?php endforeach ?></div>
<section class="card ops-card mb-3"><div class="card-body p-3 p-md-4"><h6 class="fw-bold mb-1">Atur Akses Pertemuan</h6><p class="small text-muted">Gunakan untuk membuka kembali atau mengunci akses siswa pada pengajaran tertentu.</p><form method="post" class="row g-2 align-items-end" onsubmit="return confirm('Simpan perubahan akses pertemuan ini? Tindakan akan dicatat.');"><input type="hidden" name="csrf_token" value="<?= sanitize($_SESSION['csrf_token']) ?>"><input type="hidden" name="action" value="atur_akses"><div class="col-md-6"><label class="form-label small fw-semibold">Pengajaran</label><select name="pengajaran_id" class="form-select" required><?php foreach($pengajaran as $p): ?><option value="<?= (int)$p['id'] ?>"><?= sanitize($p['nama_guru'].' · '.$p['nama_mapel'].' · '.$p['nama_kelas'].' ('.$p['semester'].' / '.$p['tahun_ajaran'].')') ?></option><?php endforeach ?></select></div><div class="col-6 col-md-2"><label class="form-label small fw-semibold">Pertemuan</label><select name="pertemuan_ke" class="form-select"><?php for($i=1;$i<=20;$i++): ?><option value="<?= $i ?>"><?= $i ?></option><?php endfor ?></select></div><div class="col-6 col-md-2"><label class="form-label small fw-semibold">Status Baru</label><select name="status" class="form-select"><option value="Dibuka">Dibuka</option><option value="Dikunci">Dikunci</option></select></div><div class="col-md-2"><button class="btn btn-danger w-100"><i class="fa-solid fa-floppy-disk me-1"></i>Simpan</button></div></form></div></section>
<section class="card ops-card mb-3"><div class="card-body p-0"><div class="px-3 px-md-4 py-3 border-bottom"><h6 class="fw-bold mb-0">Sesi Absensi Terbuka</h6><small class="text-muted">Sesi kedaluwarsa diprioritaskan untuk diperiksa.</small></div><div class="table-responsive"><table class="table ops-table table-hover mb-0"><thead class="table-light"><tr><th class="ps-4">Pengajaran</th><th>Pertemuan</th><th>Jadwal</th><th>Progres</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php foreach($sesi_terbuka as $s): ?><tr class="<?= $s['kedaluwarsa']?'critical-row':'' ?>"><td class="ps-4"><strong><?= sanitize($s['nama_mapel']) ?></strong><br><small><?= sanitize($s['nama_kelas']) ?> · <?= sanitize($s['nama_guru']) ?></small></td><td><?= (int)$s['pertemuan_ke'] ?></td><td><small><?= date('d/m/Y H:i',strtotime($s['waktu_buka'])) ?><br>s.d. <?= date('d/m/Y H:i',strtotime($s['waktu_tutup'])) ?></small></td><td><?= (int)$s['tercatat'] ?>/<?= (int)$s['total_siswa'] ?></td><td><span class="badge <?= $s['kedaluwarsa']?'bg-danger':'bg-success' ?>"><?= $s['kedaluwarsa']?'Kedaluwarsa':'Aktif' ?></span></td><td><form method="post" onsubmit="return confirm('Tutup sesi ini? Siswa yang belum check-in akan menjadi Alpa.');"><input type="hidden" name="csrf_token" value="<?= sanitize($_SESSION['csrf_token']) ?>"><input type="hidden" name="action" value="tutup_sesi"><input type="hidden" name="sesi_id" value="<?= (int)$s['id'] ?>"><button class="btn btn-sm btn-danger"><i class="fa-solid fa-lock me-1"></i>Tutup</button></form></td></tr><?php endforeach ?><?php if(!$sesi_terbuka): ?><tr><td colspan="6" class="text-center text-muted py-5">Tidak ada sesi absensi terbuka.</td></tr><?php endif ?></tbody></table></div></div></section>
<section class="card ops-card mb-3"><div class="card-body p-0"><div class="px-3 px-md-4 py-3 border-bottom"><h6 class="fw-bold mb-0">Akses Pertemuan Sedang Dibuka</h6><small class="text-muted">Admin dapat mengunci langsung akses yang tidak seharusnya masih terbuka.</small></div><div class="table-responsive"><table class="table ops-table table-hover mb-0"><thead class="table-light"><tr><th class="ps-4">Pengajaran</th><th>Pertemuan</th><th>Dibuka Pada</th><th>Aksi</th></tr></thead><tbody><?php foreach($akses_terbuka as $a): ?><tr><td class="ps-4"><strong><?= sanitize($a['nama_mapel']) ?></strong><br><small><?= sanitize($a['nama_kelas']) ?> · <?= sanitize($a['nama_guru']) ?></small></td><td><span class="badge bg-success">Pertemuan <?= (int)$a['pertemuan_ke'] ?></span></td><td><?= $a['dibuka_pada']?date('d/m/Y H:i',strtotime($a['dibuka_pada'])):'-' ?></td><td><form method="post" onsubmit="return confirm('Kunci akses pertemuan ini untuk siswa?');"><input type="hidden" name="csrf_token" value="<?= sanitize($_SESSION['csrf_token']) ?>"><input type="hidden" name="action" value="atur_akses"><input type="hidden" name="pengajaran_id" value="<?= (int)$a['pengajaran_id'] ?>"><input type="hidden" name="pertemuan_ke" value="<?= (int)$a['pertemuan_ke'] ?>"><input type="hidden" name="status" value="Dikunci"><button class="btn btn-sm btn-outline-danger"><i class="fa-solid fa-lock me-1"></i>Kunci</button></form></td></tr><?php endforeach ?><?php if(!$akses_terbuka): ?><tr><td colspan="4" class="text-center text-muted py-4">Tidak ada akses pertemuan yang sedang dibuka.</td></tr><?php endif ?></tbody></table></div></div></section>
<div class="row g-3"><div class="col-xl-7"><section class="card ops-card h-100"><div class="card-body p-0"><div class="px-3 px-md-4 py-3 border-bottom"><h6 class="fw-bold mb-0">Sesi Tertutup Tidak Lengkap</h6><small class="text-muted">Siswa tanpa detail absensi dapat disinkronkan menjadi Alpa.</small></div><div class="table-responsive"><table class="table ops-table mb-0"><thead class="table-light"><tr><th class="ps-4">Sesi</th><th>Data</th><th>Aksi</th></tr></thead><tbody><?php foreach($sesi_tidak_lengkap as $s): ?><tr><td class="ps-4"><strong><?= sanitize($s['nama_mapel']) ?></strong><br><small><?= sanitize($s['nama_kelas']) ?> · P<?= (int)$s['pertemuan_ke'] ?> · <?= date('d/m/Y',strtotime($s['tanggal'])) ?></small></td><td><span class="text-danger"><?= (int)$s['tercatat'] ?>/<?= (int)$s['total_siswa'] ?></span></td><td><form method="post" onsubmit="return confirm('Sinkronkan siswa yang belum tercatat menjadi Alpa?');"><input type="hidden" name="csrf_token" value="<?= sanitize($_SESSION['csrf_token']) ?>"><input type="hidden" name="action" value="sinkron_sesi"><input type="hidden" name="sesi_id" value="<?= (int)$s['id'] ?>"><button class="btn btn-sm btn-warning"><i class="fa-solid fa-rotate me-1"></i>Sinkronkan</button></form></td></tr><?php endforeach ?><?php if(!$sesi_tidak_lengkap): ?><tr><td colspan="3" class="text-center text-muted py-4">Semua sesi tertutup sudah lengkap.</td></tr><?php endif ?></tbody></table></div></div></section></div>
<div class="col-xl-5"><section class="card ops-card h-100"><div class="card-body p-3 p-md-4"><div class="d-flex justify-content-between"><div><h6 class="fw-bold mb-1">Audit Operasional</h6><small class="text-muted">20 tindakan admin terbaru</small></div><a href="log_aktivitas.php?q=OPERASIONAL+ADMIN" class="btn btn-sm btn-outline-primary align-self-start">Semua Log</a></div><div class="mt-2"><?php foreach($audit_operasional as $log): ?><div class="audit-item"><strong class="small"><?= sanitize($log['username']?:'Admin') ?></strong><small class="text-muted float-end"><?= date('d/m/Y H:i',strtotime($log['created_at'])) ?></small><div class="small mt-1"><?= sanitize($log['aktivitas']) ?></div><code class="small"><?= sanitize($log['ip_address']) ?></code></div><?php endforeach ?><?php if(!$audit_operasional): ?><p class="text-muted text-center py-4 mb-0">Belum ada tindakan operasional.</p><?php endif ?></div></div></section></div></div>
</main></div><?php require_once __DIR__.'/../includes/footer.php'; ?>
