<?php
require_once __DIR__.'/../includes/header.php';
require_once __DIR__.'/../config/database.php';
check_access([1]);$db=Database::getInstance();

$guru_id=(int)($_GET['guru_id']??0);$kelas_id=(int)($_GET['kelas_id']??0);$mapel_id=(int)($_GET['mapel_id']??0);
$semester=in_array($_GET['semester']??'',['Ganjil','Genap'],true)?$_GET['semester']:'';
$tahun_ajaran=trim($_GET['tahun_ajaran']??'');$jenis=in_array($_GET['jenis']??'',['Kuis','UTS','UAS'],true)?$_GET['jenis']:'';
$status_filter=in_array($_GET['status']??'',['terjadwal','aktif','selesai','belum_peserta'],true)?$_GET['status']:'';
$q=trim($_GET['q']??'');$ujian_id=(int)($_GET['ujian_id']??0);$halaman=max(1,(int)($_GET['page']??1));$per_halaman=10;
if(mb_strlen($q)>100)$q=mb_substr($q,0,100);if(mb_strlen($tahun_ajaran)>10)$tahun_ajaran='';
$guru_list=$db->query('SELECT id,nama_lengkap FROM guru ORDER BY nama_lengkap')->fetchAll();
$kelas_list=$db->query('SELECT id,nama_kelas FROM kelas ORDER BY nama_kelas')->fetchAll();
$mapel_list=$db->query('SELECT id,nama_mapel FROM mapel ORDER BY nama_mapel')->fetchAll();
$tahun_list=$db->query('SELECT DISTINCT tahun_ajaran FROM pengajaran ORDER BY tahun_ajaran DESC')->fetchAll(PDO::FETCH_COLUMN);

$where=[];$params=[];
if($guru_id){$where[]='p.guru_id=?';$params[]=$guru_id;}if($kelas_id){$where[]='p.kelas_id=?';$params[]=$kelas_id;}
if($mapel_id){$where[]='p.mapel_id=?';$params[]=$mapel_id;}if($semester!==''){$where[]='p.semester=?';$params[]=$semester;}
if($tahun_ajaran!==''){$where[]='p.tahun_ajaran=?';$params[]=$tahun_ajaran;}if($jenis!==''){$where[]='u.jenis_ujian=?';$params[]=$jenis;}
if($q!==''){$where[]='(u.nama_ujian LIKE ? OR g.nama_lengkap LIKE ? OR m.nama_mapel LIKE ? OR k.nama_kelas LIKE ?)';$cari='%'.$q.'%';array_push($params,$cari,$cari,$cari,$cari);}
$where_sql=$where?' WHERE '.implode(' AND ',$where):'';
$summary_sql="SELECT u.id,u.nama_ujian,u.jenis_ujian,u.durasi_menit,u.waktu_mulai,u.waktu_selesai,u.acak_soal,u.created_at,
 p.semester,p.tahun_ajaran,p.kelas_id,g.nama_lengkap nama_guru,m.nama_mapel,k.nama_kelas,
 (SELECT COUNT(*) FROM soal_ujian so WHERE so.ujian_id=u.id) total_soal,
 (SELECT COUNT(*) FROM soal_ujian so WHERE so.ujian_id=u.id AND so.tipe_soal='PG') soal_pg,
 (SELECT COUNT(*) FROM soal_ujian so WHERE so.ujian_id=u.id AND so.tipe_soal='ESAI') soal_esai,
 (SELECT COUNT(*) FROM siswa s WHERE s.kelas_id=p.kelas_id) total_siswa,
 (SELECT COUNT(*) FROM sesi_ujian su WHERE su.ujian_id=u.id) mulai,
 (SELECT COUNT(*) FROM sesi_ujian su WHERE su.ujian_id=u.id AND su.status='Selesai') peserta_selesai,
 (SELECT COUNT(*) FROM sesi_ujian su WHERE su.ujian_id=u.id AND su.status='Berlangsung') berlangsung,
 (SELECT AVG(nu.nilai_total) FROM nilai_ujian nu WHERE nu.ujian_id=u.id) rata_nilai
 FROM ujian u JOIN pengajaran p ON p.id=u.pengajaran_id JOIN guru g ON g.id=p.guru_id
 JOIN mapel m ON m.id=p.mapel_id JOIN kelas k ON k.id=p.kelas_id $where_sql";
$outer=[];
if($status_filter==='terjadwal')$outer[]='x.waktu_mulai>NOW()';
elseif($status_filter==='aktif')$outer[]='x.waktu_mulai<=NOW() AND x.waktu_selesai>=NOW()';
elseif($status_filter==='selesai')$outer[]='x.waktu_selesai<NOW()';
elseif($status_filter==='belum_peserta')$outer[]='x.mulai=0';
$outer_sql=$outer?' WHERE '.implode(' AND ',$outer):'';
$stmt=$db->prepare("SELECT COUNT(*) FROM ($summary_sql) x $outer_sql");$stmt->execute($params);$total_ujian=(int)$stmt->fetchColumn();
$total_halaman=max(1,(int)ceil($total_ujian/$per_halaman));$halaman=min($halaman,$total_halaman);$offset=($halaman-1)*$per_halaman;
$stmt=$db->prepare("SELECT x.*,GREATEST(x.total_siswa-x.mulai,0) belum_mulai FROM ($summary_sql) x $outer_sql ORDER BY x.waktu_mulai DESC,x.id DESC LIMIT ? OFFSET ?");
$i=1;foreach($params as $param)$stmt->bindValue($i++,$param,PDO::PARAM_STR);$stmt->bindValue($i++,$per_halaman,PDO::PARAM_INT);$stmt->bindValue($i,$offset,PDO::PARAM_INT);$stmt->execute();$ujian_list=$stmt->fetchAll();
$stmt=$db->prepare("SELECT COUNT(*) total,COALESCE(SUM(x.total_soal),0) soal,COALESCE(SUM(x.peserta_selesai),0) selesai,COALESCE(SUM(GREATEST(x.total_siswa-x.mulai,0)),0) belum FROM ($summary_sql) x $outer_sql");$stmt->execute($params);$ringkasan=$stmt->fetch();

$detail_ujian=null;$soal_list=[];$peserta=[];
if($ujian_id){
 $stmt=$db->prepare("SELECT x.*,GREATEST(x.total_siswa-x.mulai,0) belum_mulai FROM ($summary_sql) x WHERE x.id=?");$detail_params=$params;$detail_params[]=$ujian_id;$stmt->execute($detail_params);$detail_ujian=$stmt->fetch();
 if($detail_ujian){
  $stmt=$db->prepare('SELECT id,tipe_soal,pertanyaan,opsi_a,opsi_b,opsi_c,opsi_d,opsi_e,kunci_jawaban,bobot FROM soal_ujian WHERE ujian_id=? ORDER BY id');$stmt->execute([$ujian_id]);$soal_list=$stmt->fetchAll();
  $stmt=$db->prepare("SELECT su.id sesi_id,su.waktu_mulai,su.waktu_selesai,COALESCE(su.status,'Belum Mengerjakan') status,
   s.id siswa_id,s.nisn,s.nis,s.nama_lengkap,
   SUM(CASE WHEN js.id IS NOT NULL AND (js.jawaban_pg IS NOT NULL OR (js.jawaban_esai IS NOT NULL AND TRIM(js.jawaban_esai)<>'')) THEN 1 ELSE 0 END) dijawab,
   COALESCE(nu.nilai_pg,0) nilai_pg,COALESCE(nu.nilai_esai,0) nilai_esai,COALESCE(nu.nilai_total,0) nilai_total
   FROM siswa s LEFT JOIN sesi_ujian su ON su.siswa_id=s.id AND su.ujian_id=?
   LEFT JOIN jawaban_siswa js ON js.sesi_ujian_id=su.id
   LEFT JOIN nilai_ujian nu ON nu.ujian_id=? AND nu.siswa_id=s.id
   WHERE s.kelas_id=? GROUP BY s.id ORDER BY su.status='Berlangsung' DESC,su.status IS NULL DESC,s.nama_lengkap");
  $stmt->execute([$ujian_id,$ujian_id,$detail_ujian['kelas_id']]);$peserta=$stmt->fetchAll();
 }
}
$query_state=['guru_id'=>$guru_id,'kelas_id'=>$kelas_id,'mapel_id'=>$mapel_id,'semester'=>$semester,'tahun_ajaran'=>$tahun_ajaran,'jenis'=>$jenis,'status'=>$status_filter,'q'=>$q];
$filter_aktif=array_filter($query_state,static fn($v)=>$v!==''&&$v!==0);
?>
<?php require_once __DIR__.'/../includes/sidebar.php'; ?>
<div id="page-content-wrapper" class="exam-monitor-page">
<style>
.exam-monitor-page{background:#f7f9fc;min-width:0}.exam-content{max-width:1400px;margin:auto}.exam-hero{background:linear-gradient(135deg,#172554,#1d4ed8);color:#fff;border-radius:22px;padding:28px;box-shadow:0 18px 44px rgba(29,78,216,.17)}.exam-card,.metric-card{border:1px solid #e8edf5!important;border-radius:18px!important;box-shadow:0 8px 28px rgba(15,23,42,.045)!important}.metric-icon{width:44px;height:44px;display:grid;place-items:center;border-radius:13px}.filter-card .form-label{font-size:.76rem;font-weight:700}.exam-table th{white-space:nowrap;font-size:.74rem;text-transform:uppercase;color:#64748b}.exam-table td{font-size:.82rem;vertical-align:middle}.question-item{border:1px solid #e5eaf2;border-radius:14px;padding:16px}.question-item+.question-item{margin-top:10px}.option-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px}.option-item{padding:7px 9px;background:#f8fafc;border-radius:8px;font-size:.8rem}.participant-mobile{border:1px solid #e8edf5;border-radius:14px;padding:14px}.participant-mobile+.participant-mobile{margin-top:10px}.detail-anchor{scroll-margin-top:15px}.pagination .page-link{border:0;border-radius:9px!important;margin:0 2px}@media(max-width:767.98px){.exam-content{padding:14px!important}.exam-hero{padding:21px;border-radius:18px}.option-list{grid-template-columns:1fr}}
</style>
<nav class="navbar top-navbar px-3 px-md-4 py-3"><div><h5 class="fw-bold mb-0"><i class="fa-solid fa-file-circle-question text-primary me-2"></i>Monitoring Ulangan</h5><small class="text-muted">Pantau soal, peserta, pengerjaan, dan nilai</small></div></nav>
<main class="container-fluid exam-content p-3 p-md-4">
<section class="exam-hero mb-3"><div class="d-flex justify-content-between align-items-center gap-3"><div><small class="text-uppercase fw-semibold opacity-75">Kontrol CBT</small><h2 class="h4 fw-bold my-1">Ulangan dan Hasil Siswa</h2><p class="mb-0 opacity-75">Lihat kesiapan soal, progres peserta, dan hasil penilaian.</p></div><i class="fa-solid fa-chart-simple fa-2x opacity-50"></i></div></section>
<div class="row g-2 mb-3"><?php foreach([['Ulangan Ditemukan',(int)$ringkasan['total'],'fa-file-circle-question','primary'],['Total Soal',(int)$ringkasan['soal'],'fa-list-ol','info'],['Peserta Selesai',(int)$ringkasan['selesai'],'fa-circle-check','success'],['Belum Mengerjakan',(int)$ringkasan['belum'],'fa-user-clock','warning']] as [$label,$jumlah,$icon,$warna]): ?><div class="col-6 col-xl-3"><div class="card metric-card p-3 h-100"><div class="d-flex align-items-center gap-3"><span class="metric-icon bg-<?= $warna ?>-subtle text-<?= $warna ?>"><i class="fa-solid <?= $icon ?>"></i></span><div><small class="text-muted"><?= $label ?></small><h4 class="fw-bold mb-0"><?= $jumlah ?></h4></div></div></div></div><?php endforeach ?></div>
<section class="card exam-card filter-card mb-3"><div class="card-body p-3"><form method="get" class="row g-2 align-items-end">
<div class="col-md-6 col-xl-3"><label class="form-label">Cari Ulangan</label><input type="search" name="q" value="<?= sanitize($q) ?>" class="form-control" placeholder="Nama, guru, mapel, kelas..."></div>
<div class="col-6 col-md-3 col-xl"><label class="form-label">Guru</label><select name="guru_id" class="form-select"><option value="0">Semua</option><?php foreach($guru_list as $r): ?><option value="<?= (int)$r['id'] ?>" <?= $guru_id===(int)$r['id']?'selected':'' ?>><?= sanitize($r['nama_lengkap']) ?></option><?php endforeach ?></select></div>
<div class="col-6 col-md-3 col-xl"><label class="form-label">Kelas</label><select name="kelas_id" class="form-select"><option value="0">Semua</option><?php foreach($kelas_list as $r): ?><option value="<?= (int)$r['id'] ?>" <?= $kelas_id===(int)$r['id']?'selected':'' ?>><?= sanitize($r['nama_kelas']) ?></option><?php endforeach ?></select></div>
<div class="col-6 col-md-3 col-xl"><label class="form-label">Mapel</label><select name="mapel_id" class="form-select"><option value="0">Semua</option><?php foreach($mapel_list as $r): ?><option value="<?= (int)$r['id'] ?>" <?= $mapel_id===(int)$r['id']?'selected':'' ?>><?= sanitize($r['nama_mapel']) ?></option><?php endforeach ?></select></div>
<div class="col-6 col-md-3 col-xl"><label class="form-label">Semester</label><select name="semester" class="form-select"><option value="">Semua</option><option <?= $semester==='Ganjil'?'selected':'' ?>>Ganjil</option><option <?= $semester==='Genap'?'selected':'' ?>>Genap</option></select></div>
<div class="col-6 col-md-3 col-xl"><label class="form-label">Tahun</label><select name="tahun_ajaran" class="form-select"><option value="">Semua</option><?php foreach($tahun_list as $r): ?><option value="<?= sanitize($r) ?>" <?= $tahun_ajaran===$r?'selected':'' ?>><?= sanitize($r) ?></option><?php endforeach ?></select></div>
<div class="col-6 col-md-3 col-xl"><label class="form-label">Jenis</label><select name="jenis" class="form-select"><option value="">Semua</option><?php foreach(['Kuis','UTS','UAS'] as $r): ?><option value="<?= $r ?>" <?= $jenis===$r?'selected':'' ?>><?= $r ?></option><?php endforeach ?></select></div>
<div class="col-6 col-md-3 col-xl"><label class="form-label">Status</label><select name="status" class="form-select"><option value="">Semua</option><option value="terjadwal" <?= $status_filter==='terjadwal'?'selected':'' ?>>Terjadwal</option><option value="aktif" <?= $status_filter==='aktif'?'selected':'' ?>>Sedang Aktif</option><option value="selesai" <?= $status_filter==='selesai'?'selected':'' ?>>Waktu Selesai</option><option value="belum_peserta" <?= $status_filter==='belum_peserta'?'selected':'' ?>>Belum Ada Peserta</option></select></div>
<div class="col-6 col-xl-auto"><button class="btn btn-primary w-100"><i class="fa-solid fa-filter me-1"></i>Terapkan</button></div><?php if($filter_aktif): ?><div class="col-6 col-xl-auto"><a href="monitoring_ujian.php" class="btn btn-light border w-100">Reset</a></div><?php endif ?>
</form></div></section>
<?php if($detail_ujian): ?><section id="detailUjian" class="card exam-card detail-anchor mb-3"><div class="card-body p-3 p-md-4"><div class="d-flex flex-wrap justify-content-between gap-2 mb-3"><div><h6 class="fw-bold mb-1"><?= sanitize($detail_ujian['nama_ujian']) ?> <span class="badge bg-primary"><?= sanitize($detail_ujian['jenis_ujian']) ?></span></h6><small class="text-muted"><?= sanitize($detail_ujian['nama_mapel']) ?> · <?= sanitize($detail_ujian['nama_kelas']) ?> · <?= sanitize($detail_ujian['nama_guru']) ?></small></div><a href="?<?= http_build_query($query_state) ?>" class="btn btn-sm btn-light border align-self-start"><i class="fa-solid fa-xmark me-1"></i>Tutup Detail</a></div>
<ul class="nav nav-pills mb-3" role="tablist"><li class="nav-item"><button class="nav-link active" data-bs-toggle="tab" data-bs-target="#tabPeserta" type="button">Peserta (<?= count($peserta) ?>)</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#tabSoal" type="button">Soal (<?= count($soal_list) ?>)</button></li></ul>
<div class="tab-content"><div class="tab-pane fade show active" id="tabPeserta"><div class="table-responsive d-none d-md-block"><table class="table exam-table table-hover"><thead class="table-light"><tr><th>Siswa</th><th>Status</th><th>Jawaban</th><th>Waktu</th><th>Nilai PG</th><th>Nilai Esai</th><th>Total</th></tr></thead><tbody>
<?php foreach($peserta as $p): $mulai=!empty($p['sesi_id']);$kelas_status=$p['status']==='Selesai'?'bg-success':($p['status']==='Berlangsung'?'bg-warning text-dark':'bg-secondary'); ?><tr><td><strong><?= sanitize($p['nama_lengkap']) ?></strong><br><small class="text-muted"><?= sanitize($p['nisn']?:$p['nis']) ?></small></td><td><span class="badge <?= $kelas_status ?>"><?= sanitize($p['status']) ?></span></td><td><?= $mulai?(int)$p['dijawab'].' / '.count($soal_list):'—' ?></td><td><small><?= $mulai?'Mulai: '.date('d/m/Y H:i',strtotime($p['waktu_mulai'])):'Belum membuka ulangan' ?><?php if($mulai): ?><br>Selesai: <?= $p['waktu_selesai']?date('d/m/Y H:i',strtotime($p['waktu_selesai'])):'-' ?><?php endif ?></small></td><td><?= $mulai?number_format((float)$p['nilai_pg'],2,',','.'):'—' ?></td><td><?= $mulai?number_format((float)$p['nilai_esai'],2,',','.'):'—' ?></td><td><?= $mulai?'<strong class="text-primary">'.number_format((float)$p['nilai_total'],2,',','.').'</strong>':'—' ?></td></tr><?php endforeach ?></tbody></table></div>
<div class="d-md-none"><?php foreach($peserta as $p): $mulai=!empty($p['sesi_id']);$kelas_status=$p['status']==='Selesai'?'bg-success':($p['status']==='Berlangsung'?'bg-warning text-dark':'bg-secondary'); ?><article class="participant-mobile"><div class="d-flex justify-content-between gap-2"><strong><?= sanitize($p['nama_lengkap']) ?></strong><span class="badge <?= $kelas_status ?>"><?= sanitize($p['status']) ?></span></div><?php if($mulai): ?><small class="text-muted">Jawaban <?= (int)$p['dijawab'] ?>/<?= count($soal_list) ?></small><div class="row mt-2 small"><div class="col">PG <strong><?= number_format((float)$p['nilai_pg'],2,',','.') ?></strong></div><div class="col">Esai <strong><?= number_format((float)$p['nilai_esai'],2,',','.') ?></strong></div><div class="col">Total <strong class="text-primary"><?= number_format((float)$p['nilai_total'],2,',','.') ?></strong></div></div><?php else: ?><small class="text-muted">Belum membuka ulangan</small><?php endif ?></article><?php endforeach ?></div></div>
<div class="tab-pane fade" id="tabSoal"><?php foreach($soal_list as $index=>$soal): ?><article class="question-item"><div class="d-flex justify-content-between gap-2 mb-2"><span class="badge bg-primary">Soal <?= $index+1 ?> · <?= sanitize($soal['tipe_soal']) ?></span><small class="text-muted">Bobot <?= (int)$soal['bobot'] ?></small></div><div class="mb-3"><?= nl2br(sanitize($soal['pertanyaan'])) ?></div><?php if($soal['tipe_soal']==='PG'): ?><div class="option-list"><?php foreach(['A','B','C','D','E'] as $opsi): $teks=$soal['opsi_'.strtolower($opsi)];if(!$teks)continue; ?><div class="option-item <?= $soal['kunci_jawaban']===$opsi?'bg-success-subtle text-success fw-semibold':'' ?>"><?= $opsi ?>. <?= sanitize($teks) ?><?= $soal['kunci_jawaban']===$opsi?' · Kunci':'' ?></div><?php endforeach ?></div><?php else: ?><span class="badge bg-light text-dark">Jawaban dinilai manual oleh guru</span><?php endif ?></article><?php endforeach ?><?php if(!$soal_list): ?><div class="text-center text-muted py-4">Belum ada soal pada ulangan ini.</div><?php endif ?></div></div>
</div></section><?php elseif($ujian_id): ?><div class="alert alert-danger">Ulangan tidak ditemukan pada filter yang dipilih.</div><?php endif ?>
<section class="card exam-card"><div class="card-body p-0"><div class="px-3 px-md-4 py-3 border-bottom"><h6 class="fw-bold mb-0">Daftar Ulangan</h6><small class="text-muted">Menampilkan <?= $total_ujian?$offset+1:0 ?>–<?= min($offset+$per_halaman,$total_ujian) ?> dari <?= $total_ujian ?> ulangan</small></div><div class="table-responsive"><table class="table exam-table table-hover mb-0"><thead class="table-light"><tr><th class="ps-4">Ulangan</th><th>Pengajaran</th><th>Jadwal</th><th>Soal</th><th>Peserta</th><th>Nilai Rata-rata</th><th>Aksi</th></tr></thead><tbody>
<?php foreach($ujian_list as $u): $sekarang=time();$status_waktu=strtotime($u['waktu_mulai'])>$sekarang?'Terjadwal':(strtotime($u['waktu_selesai'])<$sekarang?'Selesai':'Aktif');$warna=$status_waktu==='Aktif'?'success':($status_waktu==='Terjadwal'?'primary':'secondary'); ?><tr><td class="ps-4"><strong><?= sanitize($u['nama_ujian']) ?></strong><br><span class="badge bg-light text-dark"><?= sanitize($u['jenis_ujian']) ?></span> <small><?= (int)$u['durasi_menit'] ?> menit</small></td><td><strong><?= sanitize($u['nama_mapel']) ?></strong><br><small class="text-muted"><?= sanitize($u['nama_kelas']) ?> · <?= sanitize($u['nama_guru']) ?><br><?= sanitize($u['semester']) ?> <?= sanitize($u['tahun_ajaran']) ?></small></td><td><span class="badge bg-<?= $warna ?>"><?= $status_waktu ?></span><br><small><?= date('d/m/Y H:i',strtotime($u['waktu_mulai'])) ?><br><?= date('d/m/Y H:i',strtotime($u['waktu_selesai'])) ?></small></td><td><strong><?= (int)$u['total_soal'] ?></strong><br><small>PG <?= (int)$u['soal_pg'] ?> · Esai <?= (int)$u['soal_esai'] ?></small></td><td><strong><?= (int)$u['mulai'] ?>/<?= (int)$u['total_siswa'] ?></strong> mulai<br><small class="text-success"><?= (int)$u['peserta_selesai'] ?> selesai</small> · <small class="text-warning"><?= (int)$u['berlangsung'] ?> berlangsung</small><br><small class="text-danger"><?= (int)$u['belum_mulai'] ?> belum</small></td><td><?= $u['rata_nilai']!==null?'<strong>'.number_format((float)$u['rata_nilai'],2,',','.').'</strong>':'—' ?></td><td><a href="?<?= http_build_query(array_merge($query_state,['page'=>$halaman,'ujian_id'=>(int)$u['id']])) ?>#detailUjian" class="btn btn-sm btn-primary text-nowrap"><i class="fa-solid fa-eye me-1"></i>Detail</a></td></tr><?php endforeach ?><?php if(!$ujian_list): ?><tr><td colspan="7" class="text-center text-muted py-5">Tidak ada ulangan sesuai filter.</td></tr><?php endif ?></tbody></table></div>
<?php if($total_halaman>1): ?><nav class="p-3 border-top"><ul class="pagination pagination-sm justify-content-center mb-0"><li class="page-item <?= $halaman<=1?'disabled':'' ?>"><a class="page-link" href="?<?= http_build_query(array_merge($query_state,['page'=>max(1,$halaman-1)])) ?>">&laquo;</a></li><?php for($n=max(1,$halaman-2);$n<=min($total_halaman,$halaman+2);$n++): ?><li class="page-item <?= $n===$halaman?'active':'' ?>"><a class="page-link" href="?<?= http_build_query(array_merge($query_state,['page'=>$n])) ?>"><?= $n ?></a></li><?php endfor ?><li class="page-item <?= $halaman>=$total_halaman?'disabled':'' ?>"><a class="page-link" href="?<?= http_build_query(array_merge($query_state,['page'=>min($total_halaman,$halaman+1)])) ?>">&raquo;</a></li></ul></nav><?php endif ?>
</div></section></main></div>
<?php require_once __DIR__.'/../includes/footer.php'; ?>
