<?php
require_once __DIR__.'/../config/session.php';require_once __DIR__.'/../config/auth.php';require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../config/helper.php';
check_access([1]);$db=Database::getInstance();
$jenis=in_array($_GET['jenis']??'',['kelas','guru','siswa','absensi','nilai'],true)?$_GET['jenis']:'kelas';
$format=in_array($_GET['format']??'',['excel','pdf'],true)?$_GET['format']:'';
$guru_id=(int)($_GET['guru_id']??0);$kelas_id=(int)($_GET['kelas_id']??0);$siswa_id=(int)($_GET['siswa_id']??0);
$semester=in_array($_GET['semester']??'',['Ganjil','Genap'],true)?$_GET['semester']:'';$tahun=trim($_GET['tahun_ajaran']??'');if(mb_strlen($tahun)>10)$tahun='';
$guru_list=$db->query('SELECT id,nama_lengkap FROM guru ORDER BY nama_lengkap')->fetchAll();$kelas_list=$db->query('SELECT id,nama_kelas FROM kelas ORDER BY nama_kelas')->fetchAll();$siswa_list=$db->query('SELECT s.id,s.kelas_id,s.nama_lengkap,s.nisn,k.nama_kelas FROM siswa s LEFT JOIN kelas k ON k.id=s.kelas_id ORDER BY k.nama_kelas,s.nama_lengkap')->fetchAll();$tahun_list=$db->query('SELECT DISTINCT tahun_ajaran FROM pengajaran ORDER BY tahun_ajaran DESC')->fetchAll(PDO::FETCH_COLUMN);

$pw=[];$pp=[];if($guru_id){$pw[]='guru_id=?';$pp[]=$guru_id;}if($kelas_id){$pw[]='kelas_id=?';$pp[]=$kelas_id;}if($semester){$pw[]='semester=?';$pp[]=$semester;}if($tahun){$pw[]='tahun_ajaran=?';$pp[]=$tahun;}
$stmt=$db->prepare('SELECT id FROM pengajaran'.($pw?' WHERE '.implode(' AND ',$pw):''));$stmt->execute($pp);$pids=array_map('intval',$stmt->fetchAll(PDO::FETCH_COLUMN));$pid_sql=$pids?implode(',',$pids):'0';
$judul='';$headers=[];$rows=[];$keterangan='Semester '.($semester?:'Semua').' | Tahun Ajaran '.($tahun?:'Semua');
if($format){
 if($jenis==='kelas'){
  $judul='Ringkasan Laporan Per Kelas';$headers=['No','Kelas','Jumlah Siswa','Guru Aktif','Pengajaran','Materi','Tugas','Ulangan','Sesi Absensi'];
  $where_k=$kelas_id?'WHERE k.id='.$kelas_id:'';
  $data=$db->query("SELECT k.id,k.nama_kelas,(SELECT COUNT(*) FROM siswa s WHERE s.kelas_id=k.id) siswa,(SELECT COUNT(DISTINCT p.guru_id) FROM pengajaran p WHERE p.kelas_id=k.id AND p.id IN($pid_sql)) guru,(SELECT COUNT(*) FROM pengajaran p WHERE p.kelas_id=k.id AND p.id IN($pid_sql)) pengajaran,(SELECT COUNT(*) FROM materi x WHERE x.pengajaran_id IN($pid_sql) AND EXISTS(SELECT 1 FROM pengajaran p WHERE p.id=x.pengajaran_id AND p.kelas_id=k.id)) materi,(SELECT COUNT(*) FROM tugas x WHERE x.pengajaran_id IN($pid_sql) AND EXISTS(SELECT 1 FROM pengajaran p WHERE p.id=x.pengajaran_id AND p.kelas_id=k.id)) tugas,(SELECT COUNT(*) FROM ujian x WHERE x.pengajaran_id IN($pid_sql) AND EXISTS(SELECT 1 FROM pengajaran p WHERE p.id=x.pengajaran_id AND p.kelas_id=k.id)) ujian,(SELECT COUNT(*) FROM sesi_absensi x WHERE x.pengajaran_id IN($pid_sql) AND EXISTS(SELECT 1 FROM pengajaran p WHERE p.id=x.pengajaran_id AND p.kelas_id=k.id)) absensi FROM kelas k $where_k ORDER BY k.nama_kelas")->fetchAll();
  foreach($data as $i=>$r)$rows[]=[$i+1,$r['nama_kelas'],$r['siswa'],$r['guru'],$r['pengajaran'],$r['materi'],$r['tugas'],$r['ujian'],$r['absensi']];
 }elseif($jenis==='guru'){
  $judul='Laporan Produktivitas Guru';$headers=['No','NIP','Guru','Pengajaran','Materi','Tugas','Ulangan','Absensi','Pengumpulan Dinilai','Total Pengumpulan','Progres Penilaian'];
  $where_g=$guru_id?'WHERE g.id='.$guru_id:'';
  $data=$db->query("SELECT g.id,g.nip,g.nama_lengkap,(SELECT COUNT(*) FROM pengajaran p WHERE p.guru_id=g.id AND p.id IN($pid_sql)) pengajaran,(SELECT COUNT(*) FROM materi x JOIN pengajaran p ON p.id=x.pengajaran_id WHERE p.guru_id=g.id AND p.id IN($pid_sql)) materi,(SELECT COUNT(*) FROM tugas x JOIN pengajaran p ON p.id=x.pengajaran_id WHERE p.guru_id=g.id AND p.id IN($pid_sql)) tugas,(SELECT COUNT(*) FROM ujian x JOIN pengajaran p ON p.id=x.pengajaran_id WHERE p.guru_id=g.id AND p.id IN($pid_sql)) ujian,(SELECT COUNT(*) FROM sesi_absensi x JOIN pengajaran p ON p.id=x.pengajaran_id WHERE p.guru_id=g.id AND p.id IN($pid_sql)) absensi,(SELECT COUNT(*) FROM pengumpulan_tugas pt JOIN tugas t ON t.id=pt.tugas_id JOIN pengajaran p ON p.id=t.pengajaran_id WHERE p.guru_id=g.id AND p.id IN($pid_sql) AND pt.nilai IS NOT NULL) dinilai,(SELECT COUNT(*) FROM pengumpulan_tugas pt JOIN tugas t ON t.id=pt.tugas_id JOIN pengajaran p ON p.id=t.pengajaran_id WHERE p.guru_id=g.id AND p.id IN($pid_sql)) pengumpulan FROM guru g $where_g ORDER BY g.nama_lengkap")->fetchAll();
  foreach($data as $i=>$r)$rows[]=[$i+1,$r['nip']?:'-',$r['nama_lengkap'],$r['pengajaran'],$r['materi'],$r['tugas'],$r['ujian'],$r['absensi'],$r['dinilai'],$r['pengumpulan'],number_format($r['pengumpulan']?($r['dinilai']/$r['pengumpulan'])*100:0,1,',','.').'%'];
 }elseif($jenis==='siswa'){
  $judul='Rekap Aktivitas Per Siswa';$headers=['No','NISN','Nama Siswa','Kelas','Tugas Selesai','Total Tugas','Rata-rata Tugas','Ulangan Selesai','Total Ulangan','Rata-rata Ulangan','Hadir','Sakit','Izin','Alpa','Kehadiran'];
  $sw=[];if($kelas_id)$sw[]='s.kelas_id='.$kelas_id;if($siswa_id)$sw[]='s.id='.$siswa_id;$swhere=$sw?'WHERE '.implode(' AND ',$sw):'';
  $data=$db->query("SELECT s.id,s.nisn,s.nama_lengkap,k.nama_kelas,(SELECT COUNT(pt.id) FROM tugas t JOIN pengajaran px ON px.id=t.pengajaran_id LEFT JOIN pengumpulan_tugas pt ON pt.tugas_id=t.id AND pt.siswa_id=s.id WHERE t.pengajaran_id IN($pid_sql) AND px.kelas_id=s.kelas_id AND t.deadline<=NOW()) tugas_selesai,(SELECT COUNT(*) FROM tugas t JOIN pengajaran p ON p.id=t.pengajaran_id WHERE t.pengajaran_id IN($pid_sql) AND p.kelas_id=s.kelas_id AND t.deadline<=NOW()) total_tugas,COALESCE((SELECT AVG(COALESCE(pt.nilai,0)) FROM tugas t JOIN pengajaran px ON px.id=t.pengajaran_id LEFT JOIN pengumpulan_tugas pt ON pt.tugas_id=t.id AND pt.siswa_id=s.id WHERE t.pengajaran_id IN($pid_sql) AND px.kelas_id=s.kelas_id AND t.deadline<=NOW()),0) rata_tugas,(SELECT COUNT(nu.id) FROM ujian u JOIN pengajaran px ON px.id=u.pengajaran_id LEFT JOIN nilai_ujian nu ON nu.ujian_id=u.id AND nu.siswa_id=s.id WHERE u.pengajaran_id IN($pid_sql) AND px.kelas_id=s.kelas_id AND u.waktu_selesai<=NOW()) ujian_selesai,(SELECT COUNT(*) FROM ujian u JOIN pengajaran p ON p.id=u.pengajaran_id WHERE u.pengajaran_id IN($pid_sql) AND p.kelas_id=s.kelas_id AND u.waktu_selesai<=NOW()) total_ujian,COALESCE((SELECT AVG(COALESCE(nu.nilai_total,0)) FROM ujian u JOIN pengajaran px ON px.id=u.pengajaran_id LEFT JOIN nilai_ujian nu ON nu.ujian_id=u.id AND nu.siswa_id=s.id WHERE u.pengajaran_id IN($pid_sql) AND px.kelas_id=s.kelas_id AND u.waktu_selesai<=NOW()),0) rata_ujian,(SELECT COUNT(*) FROM detail_absensi da JOIN sesi_absensi sa ON sa.id=da.sesi_absensi_id WHERE da.siswa_id=s.id AND sa.pengajaran_id IN($pid_sql) AND da.status='Hadir') hadir,(SELECT COUNT(*) FROM detail_absensi da JOIN sesi_absensi sa ON sa.id=da.sesi_absensi_id WHERE da.siswa_id=s.id AND sa.pengajaran_id IN($pid_sql) AND da.status='Sakit') sakit,(SELECT COUNT(*) FROM detail_absensi da JOIN sesi_absensi sa ON sa.id=da.sesi_absensi_id WHERE da.siswa_id=s.id AND sa.pengajaran_id IN($pid_sql) AND da.status='Izin') izin,(SELECT COUNT(*) FROM detail_absensi da JOIN sesi_absensi sa ON sa.id=da.sesi_absensi_id WHERE da.siswa_id=s.id AND sa.pengajaran_id IN($pid_sql) AND da.status='Alpa') alpa FROM siswa s LEFT JOIN kelas k ON k.id=s.kelas_id $swhere ORDER BY k.nama_kelas,s.nama_lengkap")->fetchAll();
  foreach($data as $i=>$r){$total=$r['hadir']+$r['sakit']+$r['izin']+$r['alpa'];$rows[]=[$i+1,$r['nisn'],$r['nama_lengkap'],$r['nama_kelas'],$r['tugas_selesai'],$r['total_tugas'],number_format($r['rata_tugas'],2,',','.'),$r['ujian_selesai'],$r['total_ujian'],number_format($r['rata_ujian'],2,',','.'),$r['hadir'],$r['sakit'],$r['izin'],$r['alpa'],number_format($total?($r['hadir']/$total)*100:0,1,',','.').'%'];}
 }elseif($jenis==='absensi'){
  $judul='Detail Laporan Absensi';$headers=['No','Tanggal','Pertemuan','Guru','Mapel','Kelas','NISN','Siswa','Status','Check-in','Keterangan'];
  $extra=$siswa_id?' AND s.id='.$siswa_id:'';$data=$db->query("SELECT sa.tanggal,sa.pertemuan_ke,g.nama_lengkap nama_guru,m.nama_mapel,k.nama_kelas,s.nisn,s.nama_lengkap nama_siswa,COALESCE(da.status,IF(sa.status='Ditutup','Alpa','Belum')) status,da.waktu_checkin,da.keterangan FROM sesi_absensi sa JOIN pengajaran p ON p.id=sa.pengajaran_id JOIN guru g ON g.id=p.guru_id JOIN mapel m ON m.id=p.mapel_id JOIN kelas k ON k.id=p.kelas_id JOIN siswa s ON s.kelas_id=p.kelas_id LEFT JOIN detail_absensi da ON da.sesi_absensi_id=sa.id AND da.siswa_id=s.id WHERE sa.pengajaran_id IN($pid_sql)$extra ORDER BY sa.tanggal DESC,k.nama_kelas,s.nama_lengkap")->fetchAll();
  foreach($data as $i=>$r)$rows[]=[$i+1,date('d/m/Y',strtotime($r['tanggal'])),$r['pertemuan_ke'],$r['nama_guru'],$r['nama_mapel'],$r['nama_kelas'],$r['nisn'],$r['nama_siswa'],$r['status'],$r['waktu_checkin']?date('H:i:s',strtotime($r['waktu_checkin'])):'-',$r['keterangan']?:'-'];
 }else{
  $judul='Rekap Nilai Akademik Per Mata Pelajaran';$headers=['No','NISN','Siswa','Kelas','Guru','Mapel','Semester','Tahun','Nilai Tugas','Nilai Kuis','Nilai Kehadiran','KKM'];
  $extra=$siswa_id?' AND s.id='.$siswa_id:'';
  $data=$db->query("SELECT s.nisn,s.nama_lengkap nama_siswa,k.nama_kelas,g.nama_lengkap nama_guru,m.nama_mapel,p.semester,p.tahun_ajaran,p.kkm,COALESCE((SELECT AVG(COALESCE(pt.nilai,0)) FROM tugas t LEFT JOIN pengumpulan_tugas pt ON pt.tugas_id=t.id AND pt.siswa_id=s.id WHERE t.pengajaran_id=p.id AND t.deadline<=NOW()),0) tugas,COALESCE((SELECT AVG(COALESCE(nu.nilai_total,0)) FROM ujian u LEFT JOIN nilai_ujian nu ON nu.ujian_id=u.id AND nu.siswa_id=s.id WHERE u.pengajaran_id=p.id AND u.jenis_ujian='Kuis' AND u.waktu_selesai<=NOW()),0) kuis,COALESCE((SELECT AVG(CASE WHEN da.status IN('Hadir','Sakit','Izin') THEN 100 ELSE 0 END) FROM sesi_absensi sa LEFT JOIN detail_absensi da ON da.sesi_absensi_id=sa.id AND da.siswa_id=s.id WHERE sa.pengajaran_id=p.id AND sa.status='Ditutup'),0) hadir FROM pengajaran p JOIN guru g ON g.id=p.guru_id JOIN mapel m ON m.id=p.mapel_id JOIN kelas k ON k.id=p.kelas_id JOIN siswa s ON s.kelas_id=p.kelas_id WHERE p.id IN($pid_sql)$extra ORDER BY k.nama_kelas,s.nama_lengkap,m.nama_mapel")->fetchAll();
  foreach($data as $i=>$r)$rows[]=[$i+1,$r['nisn'],$r['nama_siswa'],$r['nama_kelas'],$r['nama_guru'],$r['nama_mapel'],$r['semester'],$r['tahun_ajaran'],number_format($r['tugas'],2,',','.'),number_format($r['kuis'],2,',','.'),number_format($r['hadir'],2,',','.'),number_format($r['kkm'],2,',','.')];
 }
 $filename='Laporan_'.ucfirst($jenis).'_'.date('Ymd');$esc=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
 if($format==='excel'){header('Content-Type: application/vnd.ms-excel; charset=UTF-8');header('Content-Disposition: attachment; filename="'.$filename.'.xls"');header('Cache-Control: no-store');echo "\xEF\xBB\xBF".'<html><head><meta charset="UTF-8"><style>table{border-collapse:collapse}th,td{border:1px solid #64748b;padding:6px;white-space:nowrap}th{background:#dbeafe}</style></head><body><h2>'.$esc($judul).'</h2><p>'.$esc($keterangan).'</p><table><tr>';foreach($headers as $h)echo '<th>'.$esc($h).'</th>';echo '</tr>';foreach($rows as $row){echo '<tr>';foreach($row as $c)echo '<td>'.$esc($c).'</td>';echo '</tr>';}if(!$rows)echo '<tr><td colspan="'.count($headers).'">Tidak ada data.</td></tr>';echo '</table></body></html>';exit;}
 $pe=static function($v){$v=iconv('UTF-8','Windows-1252//TRANSLIT//IGNORE',(string)$v);return str_replace(['\\','(',')',"\r","\n"],['\\\\','\\(','\\)',' ',' '],$v);};$lines=[$judul,$keterangan,str_repeat('-',145),implode(' | ',$headers),str_repeat('-',145)];foreach($rows as $row)foreach(str_split(implode(' | ',array_map('strval',$row)),145) as $part)$lines[]=$part;if(!$rows)$lines[]='Tidak ada data.';$pages=array_chunk($lines,48);$ob=[1=>'<< /Type /Catalog /Pages 2 0 R >>',3=>'<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>'];$kids=[];$next=4;foreach($pages as $page){$po=$next++;$so=$next++;$kids[]="$po 0 R";$cmd="BT /F1 7 Tf 24 570 Td 10 TL\n";foreach($page as $line)$cmd.='('.$pe($line).") Tj T*\n";$cmd.='ET';$ob[$po]="<< /Type /Page /Parent 2 0 R /MediaBox [0 0 842 595] /Resources << /Font << /F1 3 0 R >> >> /Contents $so 0 R >>";$ob[$so]="<< /Length ".strlen($cmd)." >>\nstream\n$cmd\nendstream";}$ob[2]='<< /Type /Pages /Kids ['.implode(' ',$kids).'] /Count '.count($kids).' >>';ksort($ob);$pdf="%PDF-1.4\n";$off=[0];foreach($ob as $n=>$body){$off[$n]=strlen($pdf);$pdf.="$n 0 obj\n$body\nendobj\n";}$xref=strlen($pdf);$max=max(array_keys($ob));$pdf.="xref\n0 ".($max+1)."\n0000000000 65535 f \n";for($i=1;$i<=$max;$i++)$pdf.=sprintf('%010d 00000 n ',$off[$i])."\n";$pdf.="trailer\n<< /Size ".($max+1)." /Root 1 0 R >>\nstartxref\n$xref\n%%EOF";header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="'.$filename.'.pdf"');header('Content-Length: '.strlen($pdf));header('Cache-Control: no-store');echo $pdf;exit;
}
require_once __DIR__.'/../includes/header.php';require_once __DIR__.'/../includes/sidebar.php';
?>
<div id="page-content-wrapper" class="report-center-page"><style>
.report-center-page{background:#f7f9fc;min-width:0}.center-content{max-width:1250px;margin:auto}.center-hero{background:linear-gradient(135deg,#064e3b,#059669);color:#fff;border-radius:22px;padding:28px;box-shadow:0 18px 44px rgba(5,150,105,.17)}.center-card,.report-type{border:1px solid #e8edf5!important;border-radius:18px!important;box-shadow:0 8px 28px rgba(15,23,42,.045)!important}.report-type{padding:18px;height:100%;background:#fff}.report-icon{width:45px;height:45px;display:grid;place-items:center;border-radius:13px}.filter-note{font-size:.76rem}@media(max-width:767.98px){.center-content{padding:14px!important}.center-hero{padding:21px;border-radius:18px}}
</style><nav class="navbar top-navbar px-3 px-md-4 py-3"><div><h5 class="fw-bold mb-0"><i class="fa-solid fa-file-export text-success me-2"></i>Pusat Laporan</h5><small class="text-muted">Export laporan akademik terpusat</small></div></nav><main class="container-fluid center-content p-3 p-md-4">
<section class="center-hero mb-3"><div class="d-flex justify-content-between gap-3"><div><small class="text-uppercase fw-semibold opacity-75">Arsip dan Pelaporan</small><h2 class="h4 fw-bold my-1">Generator Laporan LMS</h2><p class="mb-0 opacity-75">Pilih cakupan, filter periode akademik, dan format dokumen.</p></div><i class="fa-solid fa-print fa-2x opacity-50"></i></div></section>
<div class="row g-2 mb-3"><?php foreach([['kelas','Ringkasan Kelas','Siswa, guru, pengajaran, dan aktivitas','fa-school','primary'],['guru','Produktivitas Guru','Konten, absensi, dan progres penilaian','fa-person-chalkboard','success'],['siswa','Rekap Siswa','Tugas, ulangan, dan kehadiran','fa-user-graduate','info'],['absensi','Detail Absensi','Status siswa setiap sesi','fa-clipboard-check','warning'],['nilai','Nilai Akademik','Nilai per siswa dan mata pelajaran','fa-graduation-cap','danger']] as [$key,$label,$desc,$icon,$color]): ?><div class="col-md-6 col-xl"><div class="report-type"><span class="report-icon bg-<?= $color ?>-subtle text-<?= $color ?> mb-3"><i class="fa-solid <?= $icon ?>"></i></span><strong class="d-block"><?= $label ?></strong><small class="text-muted"><?= $desc ?></small></div></div><?php endforeach ?></div>
<section class="card center-card"><div class="card-body p-3 p-md-4"><h6 class="fw-bold mb-1">Buat Laporan</h6><p class="text-muted small">Kosongkan filter untuk mencakup seluruh data yang tersedia.</p><form method="get" target="_blank" class="row g-3"><div class="col-md-6"><label class="form-label fw-semibold">Jenis Laporan</label><select name="jenis" class="form-select"><?php foreach(['kelas'=>'Ringkasan Per Kelas','guru'=>'Produktivitas Guru','siswa'=>'Rekap Per Siswa','absensi'=>'Detail Absensi','nilai'=>'Rekap Nilai Akademik'] as $k=>$v): ?><option value="<?= $k ?>"><?= $v ?></option><?php endforeach ?></select></div><div class="col-md-6"><label class="form-label fw-semibold">Format</label><select name="format" class="form-select"><option value="excel">Excel (.xls)</option><option value="pdf">PDF</option></select></div><div class="col-md-4"><label class="form-label fw-semibold">Guru</label><select name="guru_id" class="form-select"><option value="0">Semua Guru</option><?php foreach($guru_list as $r): ?><option value="<?= (int)$r['id'] ?>"><?= sanitize($r['nama_lengkap']) ?></option><?php endforeach ?></select></div><div class="col-md-4"><label class="form-label fw-semibold">Kelas</label><select name="kelas_id" id="kelasLaporan" class="form-select"><option value="0">Semua Kelas</option><?php foreach($kelas_list as $r): ?><option value="<?= (int)$r['id'] ?>"><?= sanitize($r['nama_kelas']) ?></option><?php endforeach ?></select></div><div class="col-md-4"><label class="form-label fw-semibold">Siswa</label><select name="siswa_id" id="siswaLaporan" class="form-select"><option value="0">Semua Siswa</option><?php foreach($siswa_list as $r): ?><option value="<?= (int)$r['id'] ?>" data-kelas="<?= (int)$r['kelas_id'] ?>"><?= sanitize($r['nama_lengkap'].' · '.($r['nama_kelas']?:'Tanpa Kelas')) ?></option><?php endforeach ?></select></div><div class="col-md-6"><label class="form-label fw-semibold">Semester</label><select name="semester" class="form-select"><option value="">Semua Semester</option><option>Ganjil</option><option>Genap</option></select></div><div class="col-md-6"><label class="form-label fw-semibold">Tahun Ajaran</label><select name="tahun_ajaran" class="form-select"><option value="">Semua Tahun</option><?php foreach($tahun_list as $r): ?><option value="<?= sanitize($r) ?>"><?= sanitize($r) ?></option><?php endforeach ?></select></div><div class="col-12"><div class="alert alert-info filter-note"><i class="fa-solid fa-circle-info me-1"></i>Filter guru, semester, dan tahun diterapkan melalui data pengajaran. Filter siswa berlaku untuk laporan siswa, absensi, dan nilai akademik.</div><button class="btn btn-success w-100 py-2"><i class="fa-solid fa-file-export me-2"></i>Buat dan Unduh Laporan</button></div></form></div></section>
</main></div><script>document.getElementById('kelasLaporan')?.addEventListener('change',function(){const k=this.value,s=document.getElementById('siswaLaporan');Array.from(s.options).forEach((o,i)=>{if(i)o.hidden=k!=='0'&&o.dataset.kelas!==k});if(s.selectedOptions[0]?.hidden)s.value='0';});</script><?php require_once __DIR__.'/../includes/footer.php'; ?>
