<?php
require_once __DIR__.'/../config/session.php';require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../config/helper.php';require_once __DIR__.'/../config/auth.php';check_access([3]);
$db=Database::getInstance();
$stmt=$db->prepare("SELECT s.id,s.nama_lengkap,s.nis,s.nisn,k.nama_kelas,k.tingkat FROM siswa s LEFT JOIN kelas k ON k.id=s.kelas_id WHERE s.user_id=?");$stmt->execute([$_SESSION['user_id']]);$siswa=$stmt->fetch();if(!$siswa){http_response_code(404);exit('Data siswa tidak ditemukan.');}
$stmt=$db->prepare("SELECT a.nama_aktivitas,a.keterangan,a.tanggal_aktivitas,a.poin,g.nama_lengkap nama_guru FROM kak_aktivitas_siswa a JOIN guru g ON g.id=a.guru_id WHERE a.siswa_id=? ORDER BY a.tanggal_aktivitas DESC,a.id DESC");$stmt->execute([(int)$siswa['id']]);$riwayat=$stmt->fetchAll();
$total_poin=array_sum(array_map(static fn($item)=>(int)$item['poin'],$riwayat));
$target_per_tingkat=['X'=>0,'XI'=>0,'XII'=>0];foreach($db->query('SELECT tingkat,target_poin FROM kak_target_tingkat')->fetchAll() as $row)$target_per_tingkat[$row['tingkat']]=(int)$row['target_poin'];
$target_poin=array_sum($target_per_tingkat);
$kekurangan=max(0,$target_poin-$total_poin);$tercapai=$target_poin>0&&$total_poin>=$target_poin;$persentase=$target_poin>0?min(100,(int)round($total_poin/$target_poin*100)):0;
?>
<?php require_once __DIR__.'/../includes/header.php';?><?php require_once __DIR__.'/../includes/sidebar.php';?>
<style>.kak-page{background:#f5f7fb;min-width:0}.kak-main{max-width:1100px;margin:auto}.kak-card{border:0;border-radius:18px;box-shadow:0 6px 22px rgba(15,23,42,.06)}.kak-summary{color:#fff;background:linear-gradient(125deg,#172554,#1d4ed8 65%,#3b82f6)}.kak-number{font-size:2.15rem;line-height:1}.kak-progress{height:10px;background:rgba(255,255,255,.2)}.kak-progress .progress-bar{background:#fbbf24}.activity-row{display:flex;gap:14px;padding:16px 0;border-bottom:1px solid #edf1f5}.activity-row:last-child{border-bottom:0}.activity-points{min-width:76px;text-align:center;border-radius:12px;padding:9px;background:#dcfce7;color:#166534;font-weight:800}.activity-copy{min-width:0;flex:1}.activity-copy strong,.activity-copy p{overflow-wrap:anywhere}@media(max-width:575.98px){.kak-main{padding:13px!important}.kak-card{border-radius:15px}.activity-row{gap:10px}.activity-points{min-width:62px;padding:8px 5px}}</style>
<div id="page-content-wrapper" class="kak-page"><nav class="navbar top-navbar px-3 px-md-4 py-3"><div><h5 class="fw-bold mb-0"><i class="fa-solid fa-medal text-warning me-2"></i>Kredit Aktivitas Siswa</h5><small class="text-muted"><?=sanitize(($siswa['nama_kelas']?:'Kelas belum ditentukan').' · Tingkat '.($siswa['tingkat']?:'-'))?></small></div></nav><main class="kak-main p-3 p-md-4">
<section class="card kak-card kak-summary mb-3"><div class="card-body p-4"><div class="row g-4 align-items-center"><div class="col-md-7"><small class="opacity-75">Total poin Kredit Aktivitas Siswa</small><div class="kak-number fw-bold my-2"><?=$total_poin?></div><div class="opacity-75">Target kumulatif kelas X–XII: <strong><?=$target_poin?> poin</strong></div><small class="d-block opacity-75 mt-2">Seluruh poin aktivitas dari kelas X sampai XII dijumlahkan.</small></div><div class="col-md-5"><div class="d-flex justify-content-between small mb-2"><span>Pencapaian kumulatif</span><strong><?=$persentase?>%</strong></div><div class="progress kak-progress mb-3" role="progressbar" aria-valuenow="<?=$persentase?>" aria-valuemin="0" aria-valuemax="100"><div class="progress-bar" style="width:<?=$persentase?>%"></div></div><?php if($target_poin===0):?><span class="badge bg-light text-dark">Target belum ditetapkan sekolah</span><?php elseif($tercapai):?><span class="badge bg-success"><i class="fa-solid fa-circle-check me-1"></i>Target kelas X–XII tercapai 100%</span><?php else:?><span class="badge bg-warning text-dark">Kurang <?=$kekurangan?> poin lagi</span><?php endif;?></div></div></div></section>
<section class="card kak-card"><div class="card-body p-3 p-md-4"><div class="d-flex justify-content-between align-items-center mb-2"><h2 class="h6 fw-bold mb-0">Riwayat Aktivitas</h2><span class="badge bg-primary-subtle text-primary"><?=count($riwayat)?> aktivitas</span></div><?php if(!$riwayat):?><div class="text-center py-5"><i class="fa-solid fa-award fa-2x text-secondary mb-3"></i><p class="text-muted mb-0">Belum ada aktivitas yang diberi poin oleh guru.</p></div><?php else:foreach($riwayat as $item):?><article class="activity-row"><div class="activity-points">+<?=(int)$item['poin']?><small class="d-block fw-normal">poin</small></div><div class="activity-copy"><strong class="d-block"><?=sanitize($item['nama_aktivitas'])?></strong><small class="text-muted"><i class="fa-regular fa-calendar me-1"></i><?=date('d M Y',strtotime($item['tanggal_aktivitas']))?> · diberikan oleh <?=sanitize($item['nama_guru'])?></small><?php if($item['keterangan']):?><p class="small text-secondary mb-0 mt-2"><?=nl2br(sanitize($item['keterangan']))?></p><?php endif;?></div></article><?php endforeach;endif;?></div></section>
</main></div><?php require_once __DIR__.'/../includes/footer.php';?>
