<?php
require_once __DIR__.'/../includes/header.php';require_once __DIR__.'/../config/database.php';check_access([3]);$db=Database::getInstance();
$stmt=$db->prepare('SELECT id,kelas_id FROM siswa WHERE user_id=?');$stmt->execute([$_SESSION['user_id']]);$siswa=$stmt->fetch();$sid=(int)($siswa['id']??0);$kelas=(int)($siswa['kelas_id']??0);
$filter=$_GET['status']??'tersedia';if(!in_array($filter,['tersedia','selesai','semua'],true))$filter='tersedia';
$where=$filter==='tersedia'?" AND u.waktu_selesai>=NOW() AND (su.id IS NULL OR su.status<>'Selesai')":($filter==='selesai'?" AND su.status='Selesai'":'');
$stmt=$db->prepare("SELECT u.id,u.nama_ujian,u.jenis_ujian,u.durasi_menit,u.waktu_mulai,u.waktu_selesai,m.nama_mapel,g.nama_lengkap nama_guru,su.status status_sesi,nu.nilai_total FROM ujian u JOIN pengajaran p ON p.id=u.pengajaran_id JOIN mapel m ON m.id=p.mapel_id JOIN guru g ON g.id=p.guru_id LEFT JOIN sesi_ujian su ON su.ujian_id=u.id AND su.siswa_id=? LEFT JOIN nilai_ujian nu ON nu.ujian_id=u.id AND nu.siswa_id=? WHERE p.kelas_id=? $where ORDER BY u.waktu_mulai DESC");
$stmt->execute([$sid,$sid,$kelas]);$list=$stmt->fetchAll();
?>
<?php require_once __DIR__.'/../includes/sidebar.php'; ?><style>.exam-list-page{background:#f5f7fb;min-width:0}.exam-list-main{max-width:1100px;margin:auto}.exam-list-card{border:0;border-radius:17px;box-shadow:0 6px 20px #0f172a0f}.exam-list-card .btn{min-height:44px}.exam-title-copy{overflow-wrap:anywhere}@media(max-width:575.98px){.exam-list-main{padding:13px!important}.exam-list-card{border-radius:14px}.exam-list-card .card-body{padding:15px!important}}</style>
<div id="page-content-wrapper" class="exam-list-page"><nav class="navbar top-navbar px-3 px-md-4 py-3"><div><h5 class="fw-bold mb-0"><i class="fa-solid fa-file-pen text-danger me-2"></i>Ulangan Harian Saya</h5><small class="text-muted">Jadwal ulangan harian kelas</small></div></nav><main class="exam-list-main p-3 p-md-4">
<div class="d-flex gap-2 overflow-auto pb-2 mb-2"><?php foreach(['tersedia'=>'Tersedia','selesai'=>'Selesai','semua'=>'Semua'] as $key=>$label): ?><a class="btn btn-sm <?= $filter===$key?'btn-primary':'btn-light' ?>" href="?status=<?= $key ?>"><?= $label ?></a><?php endforeach ?></div>
<div class="row g-3"><?php foreach($list as $u): $now=time();$mulai=strtotime($u['waktu_mulai']);$akhir=strtotime($u['waktu_selesai']);$done=$u['status_sesi']==='Selesai';$running=$now>=$mulai&&$now<=$akhir&&!$done; ?><div class="col-12 col-md-6"><article class="card exam-list-card h-100"><div class="card-body p-3 d-flex flex-column"><div class="d-flex justify-content-between gap-2 mb-2"><span class="badge bg-primary-subtle text-primary"><?= sanitize($u['nama_mapel']) ?></span><span class="badge <?= $done?'bg-success':($running?'bg-danger':'bg-secondary') ?>"><?= $done?'Selesai':($running?'Berlangsung':($now<$mulai?'Akan Datang':'Berakhir')) ?></span></div><h2 class="h6 fw-bold exam-title-copy"><?= sanitize($u['nama_ujian']) ?></h2><p class="small text-muted mb-2"><?= sanitize($u['jenis_ujian']) ?> · <?= (int)$u['durasi_menit'] ?> menit · <?= sanitize($u['nama_guru']) ?></p><div class="small border rounded p-2 mb-3 bg-light"><i class="fa-regular fa-calendar me-1"></i><?= date('d/m/Y H:i',$mulai) ?> s.d. <?= date('d/m/Y H:i',$akhir) ?></div><div class="mt-auto"><?php if($done): ?><div class="alert alert-success py-2 text-center mb-0">Sudah dikerjakan<?php if($u['nilai_total']!==null): ?> · Nilai <?= number_format($u['nilai_total'],2) ?><?php endif ?></div><?php elseif($running): ?><a class="btn btn-danger w-100" href="ujian_kerjakan.php?id=<?= (int)$u['id'] ?>"><i class="fa-solid fa-play me-1"></i><?= $u['status_sesi']==='Berlangsung'?'Lanjutkan':'Mulai' ?> Ulangan Harian</a><?php elseif($now<$mulai): ?><button class="btn btn-light w-100" disabled>Belum Dimulai</button><?php else: ?><button class="btn btn-secondary w-100" disabled>Jadwal Berakhir</button><?php endif ?></div></div></article></div><?php endforeach ?></div>
<?php if(!$list): ?><div class="card exam-list-card text-center p-5"><i class="fa-solid fa-calendar-check fa-2x text-success mb-2"></i><p class="text-muted mb-0">Tidak ada ulangan harian pada kategori ini.</p></div><?php endif ?>
</main></div><?php require_once __DIR__.'/../includes/footer.php'; ?>
