<?php
require_once __DIR__.'/../config/session.php';require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../config/helper.php';require_once __DIR__.'/../config/auth.php';check_access([2]);
$db=Database::getInstance();$stmt=$db->prepare('SELECT id,nama_lengkap FROM guru WHERE user_id=?');$stmt->execute([$_SESSION['user_id']]);$guru=$stmt->fetch();if(!$guru){http_response_code(403);exit('Data guru tidak ditemukan.');}$guru_id=(int)$guru['id'];
$success=$_SESSION['kak_success']??'';$error=$_SESSION['kak_error']??'';unset($_SESSION['kak_success'],$_SESSION['kak_error']);
if($_SERVER['REQUEST_METHOD']==='POST'){
 $action=$_POST['action']??'';
 if(!verify_csrf($_POST['csrf_token']??'')){$_SESSION['kak_error']='Sesi keamanan berakhir. Silakan muat ulang halaman.';redirect('kak.php');}
 try{
  if($action==='simpan_target'){
   $target=$_POST['target']??[];foreach(['X','XI','XII'] as $tingkat){if(!isset($target[$tingkat])||filter_var($target[$tingkat],FILTER_VALIDATE_INT,['options'=>['min_range'=>0,'max_range'=>100000]])===false)throw new InvalidArgumentException('Target poin harus berupa angka 0 sampai 100.000.');}
   $db->beginTransaction();$upsert=$db->prepare('INSERT INTO kak_target_tingkat(tingkat,target_poin,diubah_oleh) VALUES(?,?,?) ON DUPLICATE KEY UPDATE target_poin=VALUES(target_poin),diubah_oleh=VALUES(diubah_oleh)');foreach(['X','XI','XII'] as $tingkat)$upsert->execute([$tingkat,(int)$target[$tingkat],$guru_id]);$db->commit();catat_log($_SESSION['user_id'],'Memperbarui target Kredit Aktivitas Siswa tingkat X, XI, dan XII');$_SESSION['kak_success']='Target Kredit Aktivitas Siswa berhasil disimpan.';
  }elseif($action==='tambah_aktivitas'){
   $siswa_id=filter_var($_POST['siswa_id']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);$poin=filter_var($_POST['poin']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>1,'max_range'=>100000]]);$nama=trim($_POST['nama_aktivitas']??'');$ket=trim($_POST['keterangan']??'');$tanggal=trim($_POST['tanggal_aktivitas']??'');$tgl=DateTime::createFromFormat('!Y-m-d',$tanggal);
   if(!$siswa_id||!$poin||$nama===''||mb_strlen($nama)>150||mb_strlen($ket)>500||!$tgl||$tgl->format('Y-m-d')!==$tanggal)throw new InvalidArgumentException('Data aktivitas tidak lengkap atau tidak valid.');
   $cek=$db->prepare('SELECT nama_lengkap FROM siswa WHERE id=?');$cek->execute([$siswa_id]);$nama_siswa=$cek->fetchColumn();if(!$nama_siswa)throw new InvalidArgumentException('Siswa tidak ditemukan.');$ins=$db->prepare('INSERT INTO kak_aktivitas_siswa(siswa_id,guru_id,nama_aktivitas,keterangan,tanggal_aktivitas,poin) VALUES(?,?,?,?,?,?)');$ins->execute([$siswa_id,$guru_id,$nama,$ket?:null,$tanggal,$poin]);catat_log($_SESSION['user_id'],"Memberikan $poin Kredit Aktivitas Siswa kepada $nama_siswa untuk aktivitas $nama");$_SESSION['kak_success']='Aktivitas dan poin siswa berhasil ditambahkan.';
  }elseif($action==='hapus_aktivitas'){
   $id=filter_var($_POST['id']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);if(!$id)throw new InvalidArgumentException('Aktivitas tidak valid.');$del=$db->prepare('DELETE FROM kak_aktivitas_siswa WHERE id=? AND guru_id=?');$del->execute([$id,$guru_id]);if($del->rowCount()!==1)throw new InvalidArgumentException('Aktivitas tidak ditemukan atau dicatat oleh guru lain.');catat_log($_SESSION['user_id'],"Menghapus catatan Kredit Aktivitas Siswa #$id");$_SESSION['kak_success']='Catatan aktivitas berhasil dihapus.';
  }else throw new InvalidArgumentException('Aksi tidak dikenali.');
 }catch(Throwable $e){if($db->inTransaction())$db->rollBack();error_log('Proses Kredit Aktivitas Siswa gagal: '.$e->getMessage());$_SESSION['kak_error']=$e instanceof InvalidArgumentException?$e->getMessage():'Data Kredit Aktivitas Siswa gagal disimpan.';}redirect('kak.php');
}
$targets=['X'=>0,'XI'=>0,'XII'=>0];foreach($db->query('SELECT tingkat,target_poin FROM kak_target_tingkat')->fetchAll() as $row)$targets[$row['tingkat']]=(int)$row['target_poin'];
$siswa_list=$db->query('SELECT s.id,s.nama_lengkap,s.nis,k.nama_kelas,k.tingkat,COALESCE(SUM(a.poin),0) total_poin FROM siswa s LEFT JOIN kelas k ON k.id=s.kelas_id LEFT JOIN kak_aktivitas_siswa a ON a.siswa_id=s.id GROUP BY s.id,s.nama_lengkap,s.nis,k.nama_kelas,k.tingkat ORDER BY k.tingkat,k.nama_kelas,s.nama_lengkap')->fetchAll();
$riwayat=$db->query('SELECT a.*,s.nama_lengkap nama_siswa,k.nama_kelas,g.nama_lengkap nama_guru FROM kak_aktivitas_siswa a JOIN siswa s ON s.id=a.siswa_id LEFT JOIN kelas k ON k.id=s.kelas_id JOIN guru g ON g.id=a.guru_id ORDER BY a.created_at DESC,a.id DESC LIMIT 100')->fetchAll();
?>
<?php require_once __DIR__.'/../includes/header.php';?><?php require_once __DIR__.'/../includes/sidebar.php';?>
<style>
.kak-admin{background:#f5f7fb;min-width:0;overflow-x:hidden}.kak-content{width:100%;max-width:1250px;margin:auto}.kak-page-heading{min-width:0}.kak-page-heading h5{line-height:1.35}.kak-card{border:0;border-radius:17px;box-shadow:0 6px 22px rgba(15,23,42,.06)}.kak-card .form-control,.kak-card .form-select{min-height:44px;border-radius:10px}.kak-card label{margin-bottom:.4rem}.history-heading{gap:.75rem}.history-table{min-width:820px}.history-table th{white-space:nowrap;font-size:.78rem;text-transform:uppercase;letter-spacing:.025em;color:#64748b}.history-table td{vertical-align:middle}.history-table td:nth-child(3){min-width:210px;overflow-wrap:anywhere}.history-table td:last-child{width:45px}.history-table .btn{min-width:36px;min-height:36px}
@media(max-width:767.98px){.kak-content{padding:13px!important}.kak-card{border-radius:14px}.kak-card .card-body{padding:16px!important}.target-grid .col{flex:0 0 100%}.kak-card .form-control,.kak-card .form-select{font-size:16px}.history-heading{align-items:flex-start!important;flex-direction:column}.history-heading .badge{white-space:normal;text-align:left}.history-table-wrap{overflow:visible}.history-table{display:block;min-width:0;margin:0}.history-table thead{display:none}.history-table tbody{display:grid;gap:12px}.history-table tr{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px 12px;padding:14px;border:1px solid #e8edf4;border-radius:13px;background:#fff;box-shadow:0 2px 8px rgba(15,23,42,.04)}.history-table td{display:block;padding:0!important;border:0!important;min-width:0!important;overflow-wrap:anywhere}.history-table td::before{content:attr(data-label);display:block;margin-bottom:3px;font-size:.67rem;font-weight:700;letter-spacing:.04em;text-transform:uppercase;color:#94a3b8}.history-table td[data-field="student"],.history-table td[data-field="activity"]{grid-column:1/-1}.history-table td[data-field="date"],.history-table td[data-field="teacher"]{grid-column:1}.history-table td[data-field="points"]{grid-column:2;grid-row:1;text-align:right}.history-table td[data-field="points"]::before{text-align:right}.history-table td[data-field="action"]{grid-column:2;grid-row:4;align-self:end;justify-self:end}.history-table td[data-field="action"]::before{display:none}.history-table .empty-history{grid-column:1/-1;padding:24px 8px!important}.history-table .empty-history::before{display:none}}
@media(max-width:380px){.kak-content{padding:10px!important}.kak-card .card-body{padding:14px!important}.top-navbar{padding-left:12px!important;padding-right:12px!important}.kak-page-heading h5{font-size:1rem}.history-table tr{padding:12px}}
</style>
<div id="page-content-wrapper" class="kak-admin"><nav class="navbar top-navbar px-3 px-md-4 py-3"><div class="kak-page-heading"><h5 class="fw-bold mb-0"><i class="fa-solid fa-medal text-warning me-2"></i>Kredit Aktivitas Siswa</h5><small class="text-muted d-block">Atur target dan berikan poin aktivitas siswa</small></div></nav><main class="kak-content p-3 p-md-4">
<?php if($success):?><div class="alert alert-success alert-dismissible fade show"><?=sanitize($success)?><button class="btn-close" data-bs-dismiss="alert"></button></div><?php endif;?><?php if($error):?><div class="alert alert-danger alert-dismissible fade show"><?=sanitize($error)?><button class="btn-close" data-bs-dismiss="alert"></button></div><?php endif;?>
<div class="row g-3 mb-3"><div class="col-lg-5"><section class="card kak-card h-100"><div class="card-body p-4"><h2 class="h6 fw-bold mb-3">Target Minimum per Tingkat</h2><form method="post"><input type="hidden" name="csrf_token" value="<?=sanitize($_SESSION['csrf_token'])?>"><input type="hidden" name="action" value="simpan_target"><div class="row target-grid g-2"><?php foreach(['X','XI','XII'] as $tingkat):?><div class="col"><label class="form-label small fw-semibold">Tingkat <?=$tingkat?></label><div class="input-group"><input type="number" name="target[<?=$tingkat?>]" min="0" max="100000" class="form-control" value="<?=$targets[$tingkat]?>" required><span class="input-group-text">poin</span></div></div><?php endforeach;?></div><button class="btn btn-primary w-100 mt-3"><i class="fa-solid fa-floppy-disk me-1"></i>Simpan Target</button></form></div></section></div>
<div class="col-lg-7"><section class="card kak-card h-100"><div class="card-body p-4"><h2 class="h6 fw-bold mb-3">Berikan Poin Aktivitas</h2><form method="post" id="formPoin"><input type="hidden" name="csrf_token" value="<?=sanitize($_SESSION['csrf_token'])?>"><input type="hidden" name="action" value="tambah_aktivitas"><div class="mb-2"><label class="form-label fw-semibold">Siswa</label><select name="siswa_id" class="form-select" required><option value="">-- Pilih siswa --</option><?php foreach($siswa_list as $s):?><option value="<?=(int)$s['id']?>"><?=sanitize($s['nama_lengkap'].' · '.($s['nama_kelas']?:'Tanpa kelas').' · '.$s['total_poin'].' poin')?></option><?php endforeach;?></select></div><div class="row g-2"><div class="col-md-8"><label class="form-label fw-semibold">Nama aktivitas</label><input name="nama_aktivitas" maxlength="150" class="form-control" placeholder="Contoh: Lomba kebersihan antarkelas" required></div><div class="col-md-4"><label class="form-label fw-semibold">Poin</label><input type="number" name="poin" min="1" max="100000" class="form-control" required></div><div class="col-md-5"><label class="form-label fw-semibold">Tanggal aktivitas</label><input type="date" name="tanggal_aktivitas" class="form-control" value="<?=date('Y-m-d')?>" required></div><div class="col-md-7"><label class="form-label fw-semibold">Keterangan <small class="text-muted">(opsional)</small></label><input name="keterangan" maxlength="500" class="form-control"></div></div><button class="btn btn-success w-100 mt-3"><i class="fa-solid fa-plus me-1"></i>Tambahkan Aktivitas dan Poin</button></form></div></section></div></div>
<section class="card kak-card"><div class="card-body p-4"><div class="history-heading d-flex justify-content-between align-items-center mb-3"><h2 class="h6 fw-bold mb-0">Riwayat Pemberian Poin</h2><span class="badge bg-primary-subtle text-primary">100 catatan terbaru</span></div><div class="table-responsive history-table-wrap"><table class="table table-hover history-table"><thead><tr><th>Tanggal</th><th>Siswa</th><th>Aktivitas</th><th>Poin</th><th>Diberikan oleh</th><th></th></tr></thead><tbody><?php if(!$riwayat):?><tr><td colspan="6" class="empty-history text-center text-muted py-4">Belum ada riwayat aktivitas.</td></tr><?php else:foreach($riwayat as $r):?><tr><td data-label="Tanggal" data-field="date" class="text-nowrap"><?=date('d M Y',strtotime($r['tanggal_aktivitas']))?></td><td data-label="Siswa" data-field="student"><strong><?=sanitize($r['nama_siswa'])?></strong><small class="d-block text-muted"><?=sanitize($r['nama_kelas']?:'Tanpa kelas')?></small></td><td data-label="Aktivitas" data-field="activity"><?=sanitize($r['nama_aktivitas'])?><?php if($r['keterangan']):?><small class="d-block text-muted"><?=sanitize($r['keterangan'])?></small><?php endif;?></td><td data-label="Poin" data-field="points"><span class="badge bg-success-subtle text-success">+<?=(int)$r['poin']?></span></td><td data-label="Diberikan oleh" data-field="teacher"><?=sanitize($r['nama_guru'])?></td><td data-field="action"><?php if((int)$r['guru_id']===$guru_id):?><form method="post" onsubmit="return confirm('Hapus poin aktivitas ini? Total poin siswa akan ikut berkurang.')"><input type="hidden" name="csrf_token" value="<?=sanitize($_SESSION['csrf_token'])?>"><input type="hidden" name="action" value="hapus_aktivitas"><input type="hidden" name="id" value="<?=(int)$r['id']?>"><button class="btn btn-sm btn-outline-danger" aria-label="Hapus aktivitas"><i class="fa-solid fa-trash"></i></button></form><?php endif;?></td></tr><?php endforeach;endif;?></tbody></table></div></div></section>
</main></div><script>document.getElementById('formPoin')?.addEventListener('submit',function(e){if(!confirm('Tambahkan aktivitas dan poin ini kepada siswa terpilih?'))e.preventDefault();});</script><?php require_once __DIR__.'/../includes/footer.php';?>
