<?php
require_once __DIR__.'/../config/session.php';
require_once __DIR__.'/../config/auth.php';
require_once __DIR__.'/../config/helper.php';
require_once __DIR__.'/../config/database.php';
check_access([2]);

$db=Database::getInstance();
$stmt=$db->prepare('SELECT id FROM guru WHERE user_id=?');$stmt->execute([$_SESSION['user_id']]);$guru_id=(int)($stmt->fetchColumn()?:0);
if(!$guru_id){http_response_code(403);exit('Data guru tidak ditemukan.');}
$stmt=$db->prepare('SELECT p.id,m.nama_mapel,k.nama_kelas,p.semester,p.tahun_ajaran,p.kelas_id FROM pengajaran p JOIN mapel m ON m.id=p.mapel_id JOIN kelas k ON k.id=p.kelas_id WHERE p.guru_id=? ORDER BY p.tahun_ajaran DESC,p.semester,m.nama_mapel,k.nama_kelas');$stmt->execute([$guru_id]);$pengajaran=$stmt->fetchAll();
$ids=array_map(static fn(array $p):int=>(int)$p['id'],$pengajaran);$selected=(int)($_GET['pengajaran_id']??$_POST['pengajaran_id']??($ids[0]??0));if(!in_array($selected,$ids,true))$selected=0;$pertemuan=(int)($_GET['pertemuan']??$_POST['pertemuan']??1);if($pertemuan<1||$pertemuan>20)$pertemuan=1;

if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!verify_csrf($_POST['csrf_token']??'')){$_SESSION['manual_error']='Sesi keamanan berakhir. Silakan muat ulang halaman.';}
 elseif(!$selected){$_SESSION['manual_error']='Kelas dan mata pelajaran tidak valid.';}
 else{try{
  $info=array_values(array_filter($pengajaran,static fn(array $p):bool=>(int)$p['id']===$selected))[0]??null;if(!$info)throw new RuntimeException('Pengajaran bukan milik Anda.');
  $stmt=$db->prepare('SELECT id FROM siswa WHERE kelas_id=?');$stmt->execute([(int)$info['kelas_id']]);$siswa_valid=array_map('intval',$stmt->fetchAll(PDO::FETCH_COLUMN));
  $nilai_input=is_array($_POST['nilai']??null)?$_POST['nilai']:[];$catatan_input=is_array($_POST['catatan']??null)?$_POST['catatan']:[];
  $simpan=$db->prepare('INSERT INTO nilai_tugas_manual(pengajaran_id,siswa_id,pertemuan_ke,nilai,catatan,diubah_oleh) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE nilai=VALUES(nilai),catatan=VALUES(catatan),diubah_oleh=VALUES(diubah_oleh)');
  $hapus=$db->prepare('DELETE FROM nilai_tugas_manual WHERE pengajaran_id=? AND siswa_id=? AND pertemuan_ke=?');$db->beginTransaction();$jumlah=0;
  foreach($siswa_valid as $sid){$raw=trim((string)($nilai_input[$sid]??''));if($raw===''){$hapus->execute([$selected,$sid,$pertemuan]);continue;}$nilai=filter_var($raw,FILTER_VALIDATE_FLOAT);if($nilai===false||$nilai<0||$nilai>100)throw new RuntimeException('Seluruh nilai harus berada antara 0–100.');$catatan=trim((string)($catatan_input[$sid]??''));if(mb_strlen($catatan)>1000)throw new RuntimeException('Catatan maksimal 1.000 karakter.');$simpan->execute([$selected,$sid,$pertemuan,$nilai,$catatan?:null,$guru_id]);$jumlah++;}
  $db->commit();try{catat_log($_SESSION['user_id'],'Memperbarui nilai manual '.$info['nama_mapel'].' kelas '.$info['nama_kelas']);}catch(Throwable $log){error_log('Log nilai manual gagal: '.$log->getMessage());}$_SESSION['manual_success']="$jumlah nilai manual berhasil disimpan.";
 }catch(Throwable $e){if($db->inTransaction())$db->rollBack();error_log('Nilai manual gagal: '.$e->getMessage());$_SESSION['manual_error']=$e instanceof RuntimeException?$e->getMessage():'Nilai manual gagal disimpan.';}}
 header('Location: nilai_manual.php'.($selected?'?'.http_build_query(['pengajaran_id'=>$selected,'pertemuan'=>$pertemuan]):''));exit;
}

$info=null;$siswa=[];if($selected){foreach($pengajaran as $p)if((int)$p['id']===$selected){$info=$p;break;}if($info){$stmt=$db->prepare('SELECT s.id,s.nis,s.nisn,s.nama_lengkap,nm.nilai,nm.catatan,nm.updated_at FROM siswa s LEFT JOIN nilai_tugas_manual nm ON nm.siswa_id=s.id AND nm.pengajaran_id=? AND nm.pertemuan_ke=? WHERE s.kelas_id=? ORDER BY s.nama_lengkap');$stmt->execute([$selected,$pertemuan,$info['kelas_id']]);$siswa=$stmt->fetchAll();}}
$terisi=count(array_filter($siswa,static fn(array $s):bool=>$s['nilai']!==null));$success=$_SESSION['manual_success']??'';$error=$_SESSION['manual_error']??'';unset($_SESSION['manual_success'],$_SESSION['manual_error']);
?>
<?php require_once __DIR__.'/../includes/header.php';require_once __DIR__.'/../includes/sidebar.php';?>
<style>.manual-page{background:#f5f7fb;min-width:0}.manual-content{max-width:1150px;margin:auto}.manual-card{border:0;border-radius:17px;box-shadow:0 6px 22px rgba(15,23,42,.06)}.manual-score{width:100px}.manual-note{min-width:230px}.manual-table td{vertical-align:middle}.manual-save{position:sticky;bottom:0;z-index:10;background:rgba(255,255,255,.96);backdrop-filter:blur(8px);border-top:1px solid #e8edf4}@media(max-width:767.98px){.manual-content{padding:13px!important}.manual-card{border-radius:14px}.manual-card .card-body{padding:15px!important}.manual-wrap{overflow:visible}.manual-table{display:block}.manual-table thead{display:none}.manual-table tbody{display:grid;gap:12px}.manual-table tr{display:block;padding:14px;border:1px solid #e6ebf2;border-radius:13px;background:#fff}.manual-table td{display:block;padding:0 0 11px!important;border:0!important}.manual-table td:last-child{padding-bottom:0!important}.manual-table td::before{content:attr(data-label);display:block;margin-bottom:4px;font-size:.68rem;font-weight:700;text-transform:uppercase;color:#94a3b8}.manual-score,.manual-note{width:100%;min-width:0;font-size:16px}.manual-save{margin:0 -15px -15px;padding:12px 15px!important}.manual-save .btn{width:100%}}</style>
<div id="page-content-wrapper" class="manual-page"><nav class="navbar top-navbar px-3 px-md-4 py-3"><div><h5 class="fw-bold mb-0"><i class="fa-solid fa-pen-to-square text-primary me-2"></i>Input Nilai Manual</h5><small class="text-muted">Nilai tugas buku atau kegiatan kelas tanpa membuat tugas</small></div></nav><main class="manual-content p-3 p-md-4">
<?php if($success):?><div class="alert alert-success alert-dismissible fade show"><?=sanitize($success)?><button class="btn-close" data-bs-dismiss="alert"></button></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=sanitize($error)?></div><?php endif;?>
<section class="card manual-card mb-3"><div class="card-body p-3 p-md-4"><form method="get" class="row g-2"><div class="col-md-8"><label class="form-label fw-semibold">Mata Pelajaran dan Kelas yang Anda Ajar</label><select class="form-select" name="pengajaran_id" onchange="this.form.submit()"><option value="">Pilih kelas</option><?php foreach($pengajaran as $p):?><option value="<?=(int)$p['id']?>" <?=$selected===(int)$p['id']?'selected':''?>><?=sanitize($p['nama_mapel'].' — '.$p['nama_kelas'].' ('.$p['semester'].' / '.$p['tahun_ajaran'].')')?></option><?php endforeach;?></select></div><div class="col-md-4"><label class="form-label fw-semibold">Pertemuan</label><select class="form-select" name="pertemuan" onchange="this.form.submit()"><?php for($nomor=1;$nomor<=20;$nomor++):?><option value="<?=$nomor?>" <?=$pertemuan===$nomor?'selected':''?>>Pertemuan <?=$nomor?></option><?php endfor;?></select></div></form><?php if($info):?><div class="small text-muted mt-3"><strong><?=$terisi?></strong> dari <strong><?=count($siswa)?></strong> siswa sudah memiliki nilai manual pada <strong>Pertemuan <?=$pertemuan?></strong>. Nilai kosong berarti belum dinilai; angka <strong>0</strong> adalah nilai nol.</div><?php endif;?></div></section>
<?php if(!$info):?><div class="card manual-card text-center p-5 text-muted">Belum ada kelas yang dapat dipilih.</div><?php else:?><section class="card manual-card"><form method="post"><input type="hidden" name="csrf_token" value="<?=sanitize($_SESSION['csrf_token'])?>"><input type="hidden" name="pengajaran_id" value="<?=$selected?>"><div class="table-responsive manual-wrap"><table class="table table-hover manual-table mb-0"><thead class="table-light"><tr><th>No.</th><th>Siswa</th><th>Nilai Manual</th><th>Catatan</th></tr></thead><tbody><?php foreach($siswa as $i=>$s):?><tr><td data-label="Nomor"><?=$i+1?></td><td data-label="Siswa"><strong><?=sanitize($s['nama_lengkap'])?></strong><small class="d-block text-muted">NIS <?=sanitize($s['nis']?:'-')?> · NISN <?=sanitize($s['nisn']?:'-')?></small></td><td data-label="Nilai"><input class="form-control manual-score" type="number" name="nilai[<?=(int)$s['id']?>]" min="0" max="100" step="0.01" value="<?=$s['nilai']!==null?number_format((float)$s['nilai'],2,'.',''):''?>" placeholder="0–100"></td><td data-label="Catatan"><input class="form-control manual-note" name="catatan[<?=(int)$s['id']?>]" maxlength="1000" value="<?=sanitize($s['catatan']??'')?>" placeholder="Opsional"></td></tr><?php endforeach;?><?php if(!$siswa):?><tr><td colspan="4" class="text-center text-muted py-5">Belum ada siswa pada kelas ini.</td></tr><?php endif;?></tbody></table></div><div class="manual-save d-flex justify-content-end p-3"><button class="btn btn-primary" <?=!$siswa?'disabled':''?>><i class="fa-solid fa-floppy-disk me-1"></i>Simpan Semua Nilai</button></div></form></section><?php endif;?>
</main></div><?php require_once __DIR__.'/../includes/footer.php';?>
