<?php
require_once __DIR__.'/../config/session.php';require_once __DIR__.'/../config/auth.php';require_once __DIR__.'/../config/database.php';check_access([2]);
$db=Database::getInstance();$action=$_GET['action']??'';$pid=(int)($_GET['pengajaran_id']??0);if(!in_array($action,['export_excel','export_pdf'],true)||$pid<1){http_response_code(400);exit('Permintaan tidak valid.');}
$stmt=$db->prepare('SELECT id FROM guru WHERE user_id=?');$stmt->execute([$_SESSION['user_id']]);$gid=(int)$stmt->fetchColumn();
$stmt=$db->prepare('SELECT p.kelas_id,m.nama_mapel,k.nama_kelas,g.nama_lengkap nama_guru,p.semester,p.tahun_ajaran FROM pengajaran p JOIN mapel m ON m.id=p.mapel_id JOIN kelas k ON k.id=p.kelas_id JOIN guru g ON g.id=p.guru_id WHERE p.id=? AND p.guru_id=?');$stmt->execute([$pid,$gid]);$info=$stmt->fetch();if(!$info){http_response_code(403);exit('Pengajaran bukan milik Anda.');}
$stmt=$db->prepare('SELECT id,nama_komponen,bobot FROM komponen_penilaian WHERE pengajaran_id=? ORDER BY urutan,id');$stmt->execute([$pid]);$components=$stmt->fetchAll();if(abs(array_sum(array_column($components,'bobot'))-100)>.001){$_SESSION['flash_error']='Total bobot wajib tepat 100% sebelum rekap diunduh.';header('Location: rekap_nilai.php?pengajaran_id='.$pid);exit;}
$stmt=$db->prepare("SELECT s.id,s.nisn,s.nama_lengkap,
 COALESCE((SELECT AVG(COALESCE(nu.nilai_total,0)) FROM ujian u LEFT JOIN nilai_ujian nu ON nu.ujian_id=u.id AND nu.siswa_id=s.id WHERE u.pengajaran_id=? AND u.jenis_ujian='Kuis' AND u.waktu_selesai<=NOW()),0) nilai_ulangan,
 COALESCE((SELECT (SUM(COALESCE(pt.nilai,0))+COALESCE((SELECT SUM(nm.nilai) FROM nilai_tugas_manual nm WHERE nm.pengajaran_id=? AND nm.siswa_id=s.id),0))/NULLIF(COUNT(*)+(SELECT COUNT(*) FROM nilai_tugas_manual nm WHERE nm.pengajaran_id=? AND nm.siswa_id=s.id),0) FROM tugas t LEFT JOIN pengumpulan_tugas pt ON pt.tugas_id=t.id AND pt.siswa_id=s.id WHERE t.pengajaran_id=? AND t.deadline<=NOW()),0) nilai_tugas,
 COALESCE((SELECT AVG(CASE WHEN da.status IN ('Hadir','Sakit','Izin') THEN 100 ELSE 0 END)
           FROM sesi_absensi sa
           LEFT JOIN detail_absensi da ON da.sesi_absensi_id=sa.id AND da.siswa_id=s.id
           WHERE sa.pengajaran_id=? AND sa.status='Ditutup'),0) nilai_kehadiran
 FROM siswa s WHERE s.kelas_id=? ORDER BY s.nama_lengkap");
$stmt->execute([$pid,$pid,$pid,$pid,$pid,$info['kelas_id']]);$students=$stmt->fetchAll();
$stmt=$db->prepare('SELECT nk.siswa_id,nk.komponen_id,nk.nilai FROM nilai_komponen nk JOIN komponen_penilaian kp ON kp.id=nk.komponen_id WHERE kp.pengajaran_id=?');$stmt->execute([$pid]);$scores=[];foreach($stmt->fetchAll() as $n)$scores[$n['siswa_id']][$n['komponen_id']]=$n['nilai'];
$safe=preg_replace('/[^A-Za-z0-9_-]+/','_',$info['nama_kelas'].'_'.$info['nama_mapel']);$filename='Rekap_Nilai_'.trim($safe,'_').'_'.date('Ymd');
if($action==='export_excel'){$x=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_XML1,'UTF-8');$lastCol=3+count($components);header('Content-Type: application/vnd.ms-excel; charset=UTF-8');header('Content-Disposition: attachment; filename="'.$filename.'.xls"');header('Cache-Control: no-store');echo '<?xml version="1.0" encoding="UTF-8"?><?mso-application progid="Excel.Sheet"?>';?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Styles><Style ss:ID="Title"><Font ss:Bold="1" ss:Size="14"/></Style><Style ss:ID="Header"><Font ss:Bold="1"/><Interior ss:Color="#D9EAF7" ss:Pattern="Solid"/><Alignment ss:Horizontal="Center"/></Style><Style ss:ID="Weight"><Font ss:Bold="1" ss:Color="#0070C0"/><NumberFormat ss:Format="0.00%"/><Interior ss:Color="#EAF4FF" ss:Pattern="Solid"/></Style><Style ss:ID="Score"><NumberFormat ss:Format="0.00"/></Style><Style ss:ID="Manual"><NumberFormat ss:Format="0.00"/><Interior ss:Color="#FFF2CC" ss:Pattern="Solid"/></Style><Style ss:ID="Final"><Font ss:Bold="1"/><NumberFormat ss:Format="0.00"/><Interior ss:Color="#E2F0D9" ss:Pattern="Solid"/></Style></Styles><Worksheet ss:Name="Rekap Nilai"><Table>
<Column ss:Width="35"/><Column ss:Width="90"/><Column ss:Width="180"/><?php foreach($components as $c): ?><Column ss:Width="100"/><?php endforeach ?><Column ss:Width="100"/>
<Row><Cell ss:MergeAcross="<?= count($components)+3 ?>" ss:StyleID="Title"><Data ss:Type="String">REKAPITULASI NILAI SISWA - SMK JAYA BUANA</Data></Cell></Row><Row><Cell ss:MergeAcross="<?= count($components)+3 ?>"><Data ss:Type="String"><?= $x($info['nama_mapel'].' | '.$info['nama_kelas'].' | Guru: '.$info['nama_guru']) ?></Data></Cell></Row><Row><Cell ss:MergeAcross="<?= count($components)+3 ?>"><Data ss:Type="String"><?= $x('Semester '.$info['semester'].' | Tahun Ajaran '.$info['tahun_ajaran']) ?></Data></Cell></Row><Row/>
<Row><Cell/><Cell/><Cell ss:StyleID="Header"><Data ss:Type="String">BOBOT</Data></Cell><?php foreach($components as $c): ?><Cell ss:StyleID="Weight"><Data ss:Type="Number"><?= number_format($c['bobot']/100,4,'.','') ?></Data></Cell><?php endforeach ?><Cell ss:StyleID="Weight"><Data ss:Type="Number">1</Data></Cell></Row>
<Row><Cell ss:StyleID="Header"><Data ss:Type="String">No</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">NISN</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">Nama Siswa</Data></Cell><?php foreach($components as $c): ?><Cell ss:StyleID="Header"><Data ss:Type="String"><?= $x($c['nama_komponen']) ?></Data></Cell><?php endforeach ?><Cell ss:StyleID="Header"><Data ss:Type="String">Nilai Akhir</Data></Cell></Row>
<?php foreach($students as $i=>$s): ?><Row><Cell><Data ss:Type="Number"><?= $i+1 ?></Data></Cell><Cell><Data ss:Type="String"><?= $x($s['nisn']) ?></Data></Cell><Cell><Data ss:Type="String"><?= $x($s['nama_lengkap']) ?></Data></Cell><?php foreach($components as $c): $autoMap=['Ulangan Harian'=>'nilai_ulangan','Tugas Harian'=>'nilai_tugas','Kehadiran'=>'nilai_kehadiran'];$manual=!isset($autoMap[$c['nama_komponen']])||isset($scores[$s['id']][$c['id']]);$saved=$scores[$s['id']][$c['id']]??(isset($autoMap[$c['nama_komponen']])?$s[$autoMap[$c['nama_komponen']]]:null); ?><Cell ss:StyleID="<?= $manual?'Manual':'Score' ?>"><?php if($saved!==null): ?><Data ss:Type="Number"><?= number_format((float)$saved,2,'.','') ?></Data><?php elseif(!$manual): ?><Data ss:Type="Number">0</Data><?php endif ?></Cell><?php endforeach ?><Cell ss:StyleID="Final" ss:Formula="=SUMPRODUCT(RC4:RC<?= $lastCol ?>,R5C4:R5C<?= $lastCol ?>)"><Data ss:Type="Number">0</Data></Cell></Row><?php endforeach ?>
</Table><WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel"><FreezePanes/><FrozenNoSplit/><SplitHorizontal>6</SplitHorizontal><TopRowBottomPane>6</TopRowBottomPane></WorksheetOptions></Worksheet></Workbook><?php exit;}
function rntext($v){$v=iconv('UTF-8','Windows-1252//TRANSLIT//IGNORE',(string)$v);return str_replace(['\\','(',')'],['\\\\','\\(','\\)'],$v);}
$lines=['REKAPITULASI NILAI SISWA - SMK JAYA BUANA',$info['nama_mapel'].' | '.$info['nama_kelas'].' | '.$info['nama_guru'],'Semester '.$info['semester'].' | '.$info['tahun_ajaran'],str_repeat('-',115)];$heads=['No','NISN','Nama'];foreach($components as $c)$heads[]=$c['nama_komponen'].' '.$c['bobot'].'%';$heads[]='Akhir';$lines[]=implode(' | ',$heads);$lines[]=str_repeat('-',115);
foreach($students as $i=>$s){$parts=[$i+1,$s['nisn'],$s['nama_lengkap']];$final=0;foreach($components as $c){$autoMap=['Ulangan Harian'=>'nilai_ulangan','Tugas Harian'=>'nilai_tugas','Kehadiran'=>'nilai_kehadiran'];$v=(float)($scores[$s['id']][$c['id']]??(isset($autoMap[$c['nama_komponen']])?$s[$autoMap[$c['nama_komponen']]]:0));$parts[]=number_format($v,2);$final+=$v*$c['bobot']/100;}$parts[]=number_format($final,2);$text=implode(' | ',$parts);foreach(str_split($text,115) as $part)$lines[]=$part;}
$chunks=array_chunk($lines,48);$objs=[1=>'<< /Type /Catalog /Pages 2 0 R >>',3=>'<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>'];$kids=[];$n=4;foreach($chunks as $chunk){$p=$n++;$c=$n++;$kids[]="$p 0 R";$cmd="BT /F1 8 Tf 30 560 Td 11 TL\n";foreach($chunk as $line)$cmd.='('.rntext($line).") Tj T*\n";$cmd.='ET';$objs[$p]="<< /Type /Page /Parent 2 0 R /MediaBox [0 0 842 595] /Resources << /Font << /F1 3 0 R >> >> /Contents $c 0 R >>";$objs[$c]="<< /Length ".strlen($cmd)." >>\nstream\n$cmd\nendstream";}$objs[2]='<< /Type /Pages /Kids ['.implode(' ',$kids).'] /Count '.count($kids).' >>';ksort($objs);$pdf="%PDF-1.4\n";$off=[0];foreach($objs as $i=>$o){$off[$i]=strlen($pdf);$pdf.="$i 0 obj\n$o\nendobj\n";}$xref=strlen($pdf);$max=max(array_keys($objs));$pdf.="xref\n0 ".($max+1)."\n0000000000 65535 f \n";for($i=1;$i<=$max;$i++)$pdf.=sprintf('%010d 00000 n ',$off[$i])."\n";$pdf.="trailer\n<< /Size ".($max+1)." /Root 1 0 R >>\nstartxref\n$xref\n%%EOF";header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="'.$filename.'.pdf"');header('Content-Length: '.strlen($pdf));echo$pdf;
