<?php
require_once __DIR__.'/../config/session.php';require_once __DIR__.'/../config/auth.php';require_once __DIR__.'/../config/database.php';check_access([2]);
$db=Database::getInstance();$format=$_GET['format']??'';$ujianId=(int)($_GET['ujian_id']??0);$siswaId=(int)($_GET['siswa_id']??0);
if(!in_array($format,['excel','pdf'],true)||$ujianId<1){http_response_code(400);exit('Permintaan ekspor tidak valid.');}
$stmt=$db->prepare("SELECT u.id,u.nama_ujian,u.jenis_ujian,p.kelas_id,m.nama_mapel,k.nama_kelas,g.nama_lengkap nama_guru
 FROM ujian u JOIN pengajaran p ON p.id=u.pengajaran_id JOIN guru g ON g.id=p.guru_id JOIN mapel m ON m.id=p.mapel_id JOIN kelas k ON k.id=p.kelas_id
 WHERE u.id=? AND g.user_id=?");$stmt->execute([$ujianId,$_SESSION['user_id']]);$info=$stmt->fetch();if(!$info){http_response_code(403);exit('Ulangan Harian bukan milik Anda.');}
$headers=[];$rows=[];$judul='';$subjudul=$info['nama_mapel'].' | '.$info['nama_kelas'].' | Guru: '.$info['nama_guru'];
if($siswaId>0){
 $stmt=$db->prepare("SELECT su.id,s.nama_lengkap,s.nisn,su.status,su.waktu_mulai,su.waktu_selesai,COALESCE(nu.nilai_total,0) nilai_total
  FROM sesi_ujian su JOIN siswa s ON s.id=su.siswa_id LEFT JOIN nilai_ujian nu ON nu.ujian_id=su.ujian_id AND nu.siswa_id=su.siswa_id
  WHERE su.ujian_id=? AND su.siswa_id=?");$stmt->execute([$ujianId,$siswaId]);$siswa=$stmt->fetch();if(!$siswa){http_response_code(404);exit('Data siswa tidak ditemukan.');}
 $judul='Hasil Ulangan Harian - '.$siswa['nama_lengkap'];$subjudul.=' | NISN: '.$siswa['nisn'].' | Nilai: '.number_format($siswa['nilai_total'],2);
 $stmt=$db->prepare("SELECT so.tipe_soal,so.pertanyaan,so.kunci_jawaban,so.bobot,js.jawaban_pg,js.jawaban_esai,js.is_benar
  FROM soal_ujian so LEFT JOIN jawaban_siswa js ON js.soal_id=so.id AND js.sesi_ujian_id=? WHERE so.ujian_id=? ORDER BY so.id");$stmt->execute([$siswa['id'],$ujianId]);
 $headers=['No','Tipe','Pertanyaan','Jawaban Siswa','Kunci','Hasil','Bobot'];foreach($stmt->fetchAll() as $i=>$r){$jawaban=$r['tipe_soal']==='PG'?($r['jawaban_pg']??'-'):($r['jawaban_esai']?:'-');$hasil=$jawaban==='-'?'Belum Dijawab':($r['tipe_soal']==='PG'?((int)$r['is_benar']===1?'Benar':'Salah'):'Perlu Dinilai');$rows[]=[$i+1,$r['tipe_soal'],$r['pertanyaan'],$jawaban,$r['kunci_jawaban']?:'-',$hasil,$r['bobot']];}
}else{
 $judul='Rekap Hasil Kelas - '.$info['nama_ujian'];$stmt=$db->prepare("SELECT s.nisn,s.nama_lengkap,COALESCE(su.status,'Belum Mengerjakan') status,
  SUM(CASE WHEN js.id IS NOT NULL AND (js.jawaban_pg IS NOT NULL OR (js.jawaban_esai IS NOT NULL AND TRIM(js.jawaban_esai)<>'')) THEN 1 ELSE 0 END) dijawab,
  (SELECT COUNT(*) FROM soal_ujian so WHERE so.ujian_id=?) total_soal,su.waktu_mulai,su.waktu_selesai,COALESCE(nu.nilai_total,0) nilai
  FROM siswa s LEFT JOIN sesi_ujian su ON su.siswa_id=s.id AND su.ujian_id=? LEFT JOIN jawaban_siswa js ON js.sesi_ujian_id=su.id
  LEFT JOIN nilai_ujian nu ON nu.ujian_id=? AND nu.siswa_id=s.id WHERE s.kelas_id=? GROUP BY s.id ORDER BY s.nama_lengkap");$stmt->execute([$ujianId,$ujianId,$ujianId,$info['kelas_id']]);
 $headers=['No','NISN','Nama Siswa','Status','Dijawab','Total Soal','Mulai','Selesai','Nilai'];foreach($stmt->fetchAll() as $i=>$r)$rows[]=[$i+1,$r['nisn'],$r['nama_lengkap'],$r['status'],$r['dijawab'],$r['total_soal'],$r['waktu_mulai']?date('d/m/Y H:i',strtotime($r['waktu_mulai'])):'-',$r['waktu_selesai']?date('d/m/Y H:i',strtotime($r['waktu_selesai'])):'-',$r['waktu_mulai']?number_format($r['nilai'],2):'-'];
}
$safe=preg_replace('/[^A-Za-z0-9_-]+/','_',$judul);$filename=trim($safe,'_').'_'.date('Ymd');
if($format==='excel'){$x=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_XML1,'UTF-8');header('Content-Type: application/vnd.ms-excel; charset=UTF-8');header('Content-Disposition: attachment; filename="'.$filename.'.xls"');header('Cache-Control: no-store');echo '<?xml version="1.0" encoding="UTF-8"?><?mso-application progid="Excel.Sheet"?>';?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Styles><Style ss:ID="T"><Font ss:Bold="1" ss:Size="14"/></Style><Style ss:ID="H"><Font ss:Bold="1"/><Interior ss:Color="#D9EAF7" ss:Pattern="Solid"/></Style></Styles><Worksheet ss:Name="Hasil Ulangan Harian"><Table><Row><Cell ss:MergeAcross="<?= count($headers)-1 ?>" ss:StyleID="T"><Data ss:Type="String"><?= $x($judul) ?></Data></Cell></Row><Row><Cell ss:MergeAcross="<?= count($headers)-1 ?>"><Data ss:Type="String"><?= $x($info['nama_ujian'].' | '.$subjudul) ?></Data></Cell></Row><Row/><Row><?php foreach($headers as $h): ?><Cell ss:StyleID="H"><Data ss:Type="String"><?= $x($h) ?></Data></Cell><?php endforeach ?></Row><?php foreach($rows as $row): ?><Row><?php foreach($row as $v): ?><Cell><Data ss:Type="String"><?= $x($v) ?></Data></Cell><?php endforeach ?></Row><?php endforeach ?></Table></Worksheet></Workbook><?php exit;}
function uhe_text($v){$v=iconv('UTF-8','Windows-1252//TRANSLIT//IGNORE',(string)$v);return str_replace(['\\','(',')'],['\\\\','\\(','\\)'],$v);}
$lines=[$judul,$info['nama_ujian'].' | '.$subjudul,str_repeat('-',118),implode(' | ',$headers),str_repeat('-',118)];foreach($rows as $row){$line=implode(' | ',array_map('strval',$row));foreach(str_split($line,118) as $part)$lines[]=$part;}if(!$rows)$lines[]='Belum ada data.';
$pages=array_chunk($lines,48);$obj=[1=>'<< /Type /Catalog /Pages 2 0 R >>',3=>'<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>'];$kids=[];$n=4;foreach($pages as $page){$p=$n++;$c=$n++;$kids[]="$p 0 R";$cmd="BT /F1 8 Tf 30 560 Td 11 TL\n";foreach($page as $line)$cmd.='('.uhe_text($line).") Tj T*\n";$cmd.='ET';$obj[$p]="<< /Type /Page /Parent 2 0 R /MediaBox [0 0 842 595] /Resources << /Font << /F1 3 0 R >> >> /Contents $c 0 R >>";$obj[$c]="<< /Length ".strlen($cmd)." >>\nstream\n$cmd\nendstream";}$obj[2]='<< /Type /Pages /Kids ['.implode(' ',$kids).'] /Count '.count($kids).' >>';ksort($obj);$pdf="%PDF-1.4\n";$off=[0];foreach($obj as $i=>$o){$off[$i]=strlen($pdf);$pdf.="$i 0 obj\n$o\nendobj\n";}$xref=strlen($pdf);$max=max(array_keys($obj));$pdf.="xref\n0 ".($max+1)."\n0000000000 65535 f \n";for($i=1;$i<=$max;$i++)$pdf.=sprintf('%010d 00000 n ',$off[$i])."\n";$pdf.="trailer\n<< /Size ".($max+1)." /Root 1 0 R >>\nstartxref\n$xref\n%%EOF";header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="'.$filename.'.pdf"');header('Content-Length: '.strlen($pdf));echo$pdf;
