<?php
require_once __DIR__ . '/../config/session.php';
require_once __DIR__ . '/../config/auth.php';
require_once __DIR__ . '/../config/helper.php';

$isAdmin = !empty($rm_is_admin);
check_access([$isAdmin ? 1 : 2]);
$db = Database::getInstance();
$pageName = $isAdmin ? 'rekap_guru_mengajar.php' : 'rekap_mengajar.php';
$pageTitle = $isAdmin ? 'Monitoring JP Guru' : 'Rekap JP Mengajar';
$days = ['Sunday'=>'Minggu','Monday'=>'Senin','Tuesday'=>'Selasa','Wednesday'=>'Rabu','Thursday'=>'Kamis','Friday'=>'Jumat','Saturday'=>'Sabtu'];

function rm_month_valid(string $value): bool { return (bool) preg_match('/^\d{4}-(0[1-9]|1[0-2])$/', $value); }
function rm_number(mixed $value): string { return number_format((float)$value, 0, ',', '.'); }

function rm_pdf_escape(mixed $value): string {
    $value = iconv('UTF-8', 'Windows-1252//TRANSLIT//IGNORE', (string)$value);
    return str_replace(['\\','(',')'], ['\\\\','\\(','\\)'], (string)$value);
}
function rm_pdf(array $lines, string $filename): never {
    $chunks=array_chunk($lines ?: ['Tidak ada data.'],43); $objects=[1=>'<< /Type /Catalog /Pages 2 0 R >>',3=>'<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>']; $kids=[]; $number=4;
    foreach($chunks as $index=>$chunk){$page=$number++;$content=$number++;$kids[]="$page 0 R";$command="BT /F1 8 Tf 28 560 Td 11.5 TL\n";foreach($chunk as $line)$command.='('.rm_pdf_escape($line).") Tj T*\n";$command.='(Halaman '.($index+1).' dari '.count($chunks).") Tj\nET";$objects[$page]="<< /Type /Page /Parent 2 0 R /MediaBox [0 0 842 595] /Resources << /Font << /F1 3 0 R >> >> /Contents $content 0 R >>";$objects[$content]="<< /Length ".strlen($command)." >>\nstream\n$command\nendstream";}
    $objects[2]='<< /Type /Pages /Kids ['.implode(' ',$kids).'] /Count '.count($kids).' >>';ksort($objects);$pdf="%PDF-1.4\n";$offset=[0];foreach($objects as $id=>$object){$offset[$id]=strlen($pdf);$pdf.="$id 0 obj\n$object\nendobj\n";}$xref=strlen($pdf);$max=max(array_keys($objects));$pdf.="xref\n0 ".($max+1)."\n0000000000 65535 f \n";for($i=1;$i<=$max;$i++)$pdf.=sprintf('%010d 00000 n ',$offset[$i])."\n";$pdf.="trailer\n<< /Size ".($max+1)." /Root 1 0 R >>\nstartxref\n$xref\n%%EOF";
    header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="'.$filename.'.pdf"');header('Content-Length: '.strlen($pdf));header('Cache-Control: no-store');echo $pdf;exit;
}
function rm_locked(PDO $db,int $guruId,string $date): bool {
    $stmt=$db->prepare("SELECT EXISTS(SELECT 1 FROM validasi_rekap_mengajar v JOIN users u ON u.id=v.divalidasi_oleh AND u.role_id=1 WHERE v.guru_id=? AND v.periode_bulan=DATE_FORMAT(?,'%Y-%m-01'))");$stmt->execute([$guruId,$date]);return (bool)$stmt->fetchColumn();
}

$ownGuruId=0;
if(!$isAdmin){$stmt=$db->prepare('SELECT id FROM guru WHERE user_id=?');$stmt->execute([$_SESSION['user_id']]);$ownGuruId=(int)$stmt->fetchColumn();if(!$ownGuruId){http_response_code(403);exit('Profil Guru tidak ditemukan.');}}
$month=is_string($_GET['bulan']??null)?trim($_GET['bulan']):date('Y-m');if(!rm_month_valid($month))$month=date('Y-m');
$monthStart=$month.'-01';$monthEnd=date('Y-m-t',strtotime($monthStart));
// Rentang tanggal hanya untuk tampilan guru; validasi admin tetap per bulan.
$isRange = !$isAdmin && ($_GET['periode'] ?? '') === 'rentang';
$periodStart = $monthStart;
$periodEnd = $monthEnd;
$periodError = '';
if ($isRange) {
    $startInput = is_string($_GET['tanggal_mulai'] ?? null) ? trim($_GET['tanggal_mulai']) : '';
    $endInput = is_string($_GET['tanggal_selesai'] ?? null) ? trim($_GET['tanggal_selesai']) : '';
    $validDate = static function(string $value): bool {
        if (!preg_match('/^[1-9][0-9]{3}-[0-9]{2}-[0-9]{2}$/', $value)) return false;
        $date = DateTimeImmutable::createFromFormat('!Y-m-d', $value);
        return $date && $date->format('Y-m-d') === $value;
    };
    if (!$validDate($startInput) || !$validDate($endInput)) {
        $periodError = 'Tanggal mulai dan tanggal selesai wajib diisi dengan tanggal yang valid.';
    } elseif ($startInput > $endInput) {
        $periodError = 'Tanggal mulai tidak boleh melewati tanggal selesai.';
    } else {
        $periodStart = $startInput;
        $periodEnd = $endInput;
    }
    if ($periodError && in_array($_GET['format'] ?? '', ['excel','pdf'], true)) {
        http_response_code(400);
        header('Content-Type: text/plain; charset=utf-8');
        exit($periodError);
    }
}
$periodLabel = $isRange ? date('d/m/Y',strtotime($periodStart)).' - '.date('d/m/Y',strtotime($periodEnd)) : date('m/Y',strtotime($monthStart));
$totalLabel = $isRange ? 'Total JP Periode' : 'Total JP Bulan';

$teacherFilter=$isAdmin?max(0,(int)($_GET['guru_id']??0)):$ownGuruId;
$classFilter=max(0,(int)($_GET['kelas_id']??0));$subjectFilter=max(0,(int)($_GET['mapel_id']??0));

if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!verify_csrf($_POST['csrf_token']??'')){$_SESSION['flash_error']='Token keamanan tidak valid.';redirect($pageName.'?bulan='.$month);}
    try{
        $action=$_POST['action']??'';
        if($action==='validate'){
            if(!$isAdmin)throw new InvalidArgumentException('Validasi hanya dapat dilakukan oleh admin.');
            $guruId=(int)($_POST['guru_id']??0);$period=trim($_POST['periode_bulan']??'');if($guruId<1||!rm_month_valid($period))throw new InvalidArgumentException('Data validasi tidak valid.');$startPeriod=$period.'-01';$endPeriod=date('Y-m-t',strtotime($startPeriod));
            $stmt=$db->prepare('SELECT COALESCE(SUM(r.jumlah_jp),0) FROM rekap_mengajar r JOIN pengajaran p ON p.id=r.pengajaran_id WHERE p.guru_id=? AND r.tanggal BETWEEN ? AND ?');$stmt->execute([$guruId,$startPeriod,$endPeriod]);$total=(float)$stmt->fetchColumn();if($total<=0)throw new InvalidArgumentException('Belum ada JP yang dapat divalidasi.');
            $stmt=$db->prepare('INSERT INTO validasi_rekap_mengajar(guru_id,periode_bulan,total_jp,divalidasi_oleh,divalidasi_pada) VALUES(?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE total_jp=VALUES(total_jp),divalidasi_oleh=VALUES(divalidasi_oleh),divalidasi_pada=NOW()');$stmt->execute([$guruId,$startPeriod,$total,$_SESSION['user_id']]);catat_log($_SESSION['user_id'],"Admin memvalidasi rekap guru ID $guruId periode $period sejumlah $total JP");$_SESSION['flash_success']='Rekap bulanan berhasil divalidasi admin dan dikunci.';
        }elseif($action==='revoke'){
            if(!$isAdmin)throw new InvalidArgumentException('Aksi tidak diizinkan.');$guruId=(int)($_POST['guru_id']??0);$period=trim($_POST['periode_bulan']??'');if($guruId<1||!rm_month_valid($period))throw new InvalidArgumentException('Data validasi tidak valid.');
            $stmt=$db->prepare('DELETE FROM validasi_rekap_mengajar WHERE guru_id=? AND periode_bulan=?');$stmt->execute([$guruId,$period.'-01']);if(!$stmt->rowCount())throw new InvalidArgumentException('Validasi tidak ditemukan.');catat_log($_SESSION['user_id'],"Admin membatalkan validasi guru ID $guruId periode $period");$_SESSION['flash_success']='Validasi dibatalkan. Setelah koreksi, admin perlu memvalidasi kembali.';
        }elseif(in_array($action,['save','delete'],true)){
            if(!$isAdmin)throw new InvalidArgumentException('Aksi tidak diizinkan.');
            if($action==='delete'){
                $id=(int)($_POST['id']??0);$stmt=$db->prepare('SELECT p.guru_id,r.tanggal FROM rekap_mengajar r JOIN pengajaran p ON p.id=r.pengajaran_id WHERE r.id=?');$stmt->execute([$id]);$old=$stmt->fetch();if(!$old)throw new InvalidArgumentException('Catatan tidak ditemukan.');if(rm_locked($db,(int)$old['guru_id'],$old['tanggal']))throw new InvalidArgumentException('Rekap bulan ini sudah divalidasi dan dikunci.');$db->prepare('DELETE FROM rekap_mengajar WHERE id=?')->execute([$id]);catat_log($_SESSION['user_id'],"Menghapus realisasi mengajar ID: $id");$_SESSION['flash_success']='Catatan JP berhasil dihapus.';
            }else{
                $id=(int)($_POST['id']??0);$teachingId=(int)($_POST['pengajaran_id']??0);$date=trim($_POST['tanggal']??'');$session=$_POST['jenis_sesi']??'';$first=(int)($_POST['jam_ke_mulai']??0);$last=(int)($_POST['jam_ke_selesai']??0);$validDate=DateTime::createFromFormat('!Y-m-d',$date);
                if(!$validDate||$validDate->format('Y-m-d')!==$date||!in_array($session,['Pagi','Siang'],true)||$first<1||$first>6||$last<$first||$last>6)throw new InvalidArgumentException('Tanggal, sesi, atau rentang jam pelajaran tidak valid.');
                $stmt=$db->prepare('SELECT guru_id FROM pengajaran WHERE id=?');$stmt->execute([$teachingId]);$guruId=(int)$stmt->fetchColumn();if(!$guruId)throw new InvalidArgumentException('Pengajaran tidak ditemukan.');if(rm_locked($db,$guruId,$date))throw new InvalidArgumentException('Rekap guru pada bulan ini sudah divalidasi dan dikunci.');
                if($id){$stmt=$db->prepare('SELECT p.guru_id,r.tanggal FROM rekap_mengajar r JOIN pengajaran p ON p.id=r.pengajaran_id WHERE r.id=?');$stmt->execute([$id]);$old=$stmt->fetch();if(!$old)throw new InvalidArgumentException('Catatan tidak ditemukan.');if(rm_locked($db,(int)$old['guru_id'],$old['tanggal']))throw new InvalidArgumentException('Catatan lama berada pada bulan yang dikunci.');}
                $overlap=$db->prepare('SELECT COUNT(*) FROM rekap_mengajar r JOIN pengajaran p ON p.id=r.pengajaran_id WHERE p.guru_id=? AND r.tanggal=? AND r.jenis_sesi=? AND r.id<>? AND r.jam_ke_mulai<=? AND r.jam_ke_selesai>=?');$overlap->execute([$guruId,$date,$session,$id,$last,$first]);if((int)$overlap->fetchColumn()>0)throw new InvalidArgumentException('Guru sudah memiliki catatan yang bertumpuk pada hari, sesi, dan jam tersebut.');
                $jp=$last-$first+1;$legacyStart=sprintf('%02d:00',$first);$legacyEnd=sprintf('%02d:00',$last+1);$legacySession="$session - Jam ke-$first s.d. $last";
                if($id){$stmt=$db->prepare('UPDATE rekap_mengajar SET pengajaran_id=?,tanggal=?,jenis_sesi=?,jam_ke_mulai=?,jam_ke_selesai=?,jam_mulai=?,jam_selesai=?,sesi=?,jumlah_jp=? WHERE id=?');$stmt->execute([$teachingId,$date,$session,$first,$last,$legacyStart,$legacyEnd,$legacySession,$jp,$id]);catat_log($_SESSION['user_id'],"Mengubah realisasi mengajar ID: $id");$_SESSION['flash_success']='Catatan JP berhasil diperbarui.';}
                else{$stmt=$db->prepare('INSERT INTO rekap_mengajar(pengajaran_id,tanggal,jenis_sesi,jam_ke_mulai,jam_ke_selesai,jam_mulai,jam_selesai,sesi,jumlah_jp,dibuat_oleh) VALUES(?,?,?,?,?,?,?,?,?,?)');$stmt->execute([$teachingId,$date,$session,$first,$last,$legacyStart,$legacyEnd,$legacySession,$jp,$_SESSION['user_id']]);catat_log($_SESSION['user_id'],'Menambahkan realisasi mengajar ID: '.$db->lastInsertId());$_SESSION['flash_success']="$jp JP berhasil dicatat.";}
            }
        }else throw new InvalidArgumentException('Aksi tidak dikenali.');
    }catch(InvalidArgumentException $e){$_SESSION['flash_error']=$e->getMessage();}catch(Throwable $e){error_log('Rekap mengajar: '.$e->getMessage());$_SESSION['flash_error']='Data gagal diproses. Pastikan migrasi terbaru sudah dijalankan.';}
    redirect($pageName.'?'.http_build_query(array_filter(['bulan'=>$month,'guru_id'=>$teacherFilter?:null,'kelas_id'=>$classFilter?:null,'mapel_id'=>$subjectFilter?:null])));
}

$where=['r.tanggal BETWEEN ? AND ?'];$params=[$periodStart,$periodEnd];foreach([['p.guru_id',$teacherFilter],['p.kelas_id',$classFilter],['p.mapel_id',$subjectFilter]] as [$column,$value])if($value){$where[]="$column=?";$params[]=$value;}if($periodError)$where[]='1=0';$whereSql=implode(' AND ',$where);
$joins=' FROM rekap_mengajar r JOIN pengajaran p ON p.id=r.pengajaran_id JOIN guru g ON g.id=p.guru_id JOIN kelas k ON k.id=p.kelas_id JOIN mapel m ON m.id=p.mapel_id ';
$select='SELECT r.id,r.pengajaran_id,r.tanggal,COALESCE(r.jenis_sesi,IF(HOUR(r.jam_mulai)<12,"Pagi","Siang")) jenis_sesi,COALESCE(r.jam_ke_mulai,1) jam_ke_mulai,COALESCE(r.jam_ke_selesai,GREATEST(1,ROUND(r.jumlah_jp))) jam_ke_selesai,r.jumlah_jp,p.semester,p.tahun_ajaran,g.id guru_id,g.nip,g.nama_lengkap,k.nama_kelas,m.nama_mapel';
$stmt=$db->prepare($select.$joins.' WHERE '.$whereSql.' ORDER BY g.nama_lengkap,m.nama_mapel,r.tanggal,r.jenis_sesi,r.jam_ke_mulai');$stmt->execute($params);$details=$stmt->fetchAll();
// Monthly totals always include every subject and class taught by the teacher.
$monthlyWhere=['r.tanggal BETWEEN ? AND ?'];$monthlyParams=[$periodStart,$periodEnd];if($periodError)$monthlyWhere[]='1=0';
if($teacherFilter){$monthlyWhere[]='p.guru_id=?';$monthlyParams[]=$teacherFilter;}
$stmt=$db->prepare('SELECT g.id guru_id,g.nama_lengkap,SUM(r.jumlah_jp) total_jp FROM rekap_mengajar r JOIN pengajaran p ON p.id=r.pengajaran_id JOIN guru g ON g.id=p.guru_id WHERE '.implode(' AND ',$monthlyWhere).' GROUP BY g.id,g.nama_lengkap ORDER BY g.nama_lengkap');$stmt->execute($monthlyParams);$monthly=$stmt->fetchAll();
$totalMonthly=array_sum(array_column($monthly,'total_jp'));
$stmt=$db->prepare('SELECT r.tanggal,g.id guru_id,g.nama_lengkap,SUM(r.jumlah_jp) total_jp'.$joins.' WHERE '.$whereSql.' GROUP BY r.tanggal,g.id,g.nama_lengkap ORDER BY r.tanggal DESC,g.nama_lengkap');$stmt->execute($params);$daily=$stmt->fetchAll();
$validationSql='SELECT v.*,g.nama_lengkap FROM validasi_rekap_mengajar v JOIN guru g ON g.id=v.guru_id JOIN users u ON u.id=v.divalidasi_oleh AND u.role_id=1 WHERE v.periode_bulan BETWEEN ? AND ?';$validationParams=[substr($periodStart,0,7).'-01',substr($periodEnd,0,7).'-01'];if($teacherFilter){$validationSql.=' AND v.guru_id=?';$validationParams[]=$teacherFilter;}$validationSql.=' ORDER BY g.nama_lengkap';$stmt=$db->prepare($validationSql);$stmt->execute($validationParams);$validations=$stmt->fetchAll();$validationByTeacher=[];$validationByMonth=[];
foreach($validations as $v){$validationByTeacher[(int)$v['guru_id']]=$v;$validationByMonth[(int)$v['guru_id']][substr($v['periode_bulan'],0,7)]=$v;}
if($isRange){
    $validationByTeacher=[];
    $stmt=$db->prepare("SELECT DISTINCT g.id guru_id,DATE_FORMAT(r.tanggal,'%Y-%m') periode FROM rekap_mengajar r JOIN pengajaran p ON p.id=r.pengajaran_id JOIN guru g ON g.id=p.guru_id WHERE ".implode(' AND ',$monthlyWhere));
    $stmt->execute($monthlyParams);$teacherMonths=[];
    foreach($stmt->fetchAll() as $row)$teacherMonths[(int)$row['guru_id']][]=$row['periode'];
    foreach($teacherMonths as $gid=>$months){
        $allValidated=true;
        foreach($months as $key)if(!isset($validationByMonth[$gid][$key])){$allValidated=false;break;}
        if($allValidated)$validationByTeacher[$gid]=['range'=>true];
    }
}

$totalActual=array_sum(array_column($details,'jumlah_jp'));$teacherCount=count(array_unique(array_column($details,'guru_id')));$dayCount=count(array_unique(array_column($details,'tanggal')));
$state=array_filter(['periode'=>$isRange?'rentang':null,'tanggal_mulai'=>$isRange?$periodStart:null,'tanggal_selesai'=>$isRange?$periodEnd:null,'bulan'=>$isRange?null:$month,'guru_id'=>$isAdmin?$teacherFilter:null,'kelas_id'=>$classFilter,'mapel_id'=>$subjectFilter],static fn($v)=>$v!==null&&$v!==0&&$v!=='');

if(in_array($_GET['format']??'',['excel','pdf'],true)){
    $filename=($isAdmin?'Rekap_JP_Guru_':'Rekap_JP_Saya_').str_replace('-','_',$isRange?$periodStart.'_sd_'.$periodEnd:$month);$title='REKAP JP GURU - '.$periodLabel;
    if($_GET['format']==='excel'){header('Content-Type: application/vnd.ms-excel; charset=UTF-8');header('Content-Disposition: attachment; filename="'.$filename.'.xls"');header('Cache-Control: no-store');echo "\xEF\xBB\xBF";?><table border="1"><tr><th colspan="10"><?= sanitize($title) ?></th></tr><tr><th>No</th><th>Hari</th><th>Tanggal</th><th>Guru</th><th>Mapel</th><th>Kelas</th><th>Sesi</th><th>Jam Ke</th><th>JP</th><th>Status</th></tr><?php foreach($details as $i=>$r):?><tr><td><?= $i+1 ?></td><td><?= $days[date('l',strtotime($r['tanggal']))] ?></td><td><?= date('d/m/Y',strtotime($r['tanggal'])) ?></td><td><?= sanitize($r['nama_lengkap']) ?></td><td><?= sanitize($r['nama_mapel']) ?></td><td><?= sanitize($r['nama_kelas']) ?></td><td><?= sanitize($r['jenis_sesi']) ?></td><td><?= (int)$r['jam_ke_mulai'] ?>-<?= (int)$r['jam_ke_selesai'] ?></td><td><?= (float)$r['jumlah_jp'] ?></td><td><?= isset($validationByMonth[(int)$r['guru_id']][substr($r['tanggal'],0,7)])?'Divalidasi Admin':'Belum Divalidasi' ?></td></tr><?php endforeach?><tr><th colspan="8">TOTAL JP</th><th><?= $totalActual ?></th><th></th></tr><tr></tr><tr><th>Guru</th><th><?= sanitize($totalLabel) ?></th></tr><?php foreach($monthly as $r):?><tr><td><?= sanitize($r['nama_lengkap']) ?></td><td><?= (float)$r['total_jp'] ?></td></tr><?php endforeach?></table><?php exit;}
    $lines=[$title,'Periode: '.$periodLabel,'Total: '.rm_number($totalActual).' JP',str_repeat('-',125),sprintf('%-3s %-10s %-20s %-22s %-13s %-12s %4s','No','Tanggal','Guru','Mata Pelajaran','Kelas','Sesi/Jam','JP'),str_repeat('-',125)];$short=static fn($v,$w)=>function_exists('mb_strimwidth')?mb_strimwidth($v,0,$w,'..','UTF-8'):substr($v,0,$w);foreach($details as $i=>$r)$lines[]=sprintf('%-3d %-10s %-20s %-22s %-13s %-12s %4s',$i+1,date('d/m/Y',strtotime($r['tanggal'])),$short($r['nama_lengkap'],20),$short($r['nama_mapel'],22),$short($r['nama_kelas'],13),$r['jenis_sesi'].' '.$r['jam_ke_mulai'].'-'.$r['jam_ke_selesai'],rm_number($r['jumlah_jp']));$lines[]=str_repeat('-',125);$lines[]='TOTAL '.rm_number($totalActual).' JP';$lines[]='';$lines[]=($isRange?'REKAP PERIODE':'REKAP BULANAN').' PER GURU (SEMUA MATA PELAJARAN DAN KELAS)';$lines[]='Guru | '.$totalLabel;foreach($monthly as $r)$lines[]=$r['nama_lengkap'].' | '.rm_number($r['total_jp']).' JP';rm_pdf($lines,$filename);
}

$teachers=$isAdmin?$db->query('SELECT id,nama_lengkap FROM guru ORDER BY nama_lengkap')->fetchAll():[];
if($isAdmin){$classes=$db->query('SELECT id,nama_kelas FROM kelas ORDER BY nama_kelas')->fetchAll();$subjects=$db->query('SELECT id,nama_mapel FROM mapel ORDER BY nama_mapel')->fetchAll();}
else{$stmt=$db->prepare('SELECT DISTINCT k.id,k.nama_kelas FROM pengajaran p JOIN kelas k ON k.id=p.kelas_id WHERE p.guru_id=? ORDER BY k.nama_kelas');$stmt->execute([$ownGuruId]);$classes=$stmt->fetchAll();$stmt=$db->prepare('SELECT DISTINCT m.id,m.nama_mapel FROM pengajaran p JOIN mapel m ON m.id=p.mapel_id WHERE p.guru_id=? ORDER BY m.nama_mapel');$stmt->execute([$ownGuruId]);$subjects=$stmt->fetchAll();}
$teachingSql='SELECT p.id,p.guru_id,p.mapel_id,p.kelas_id,p.semester,p.tahun_ajaran,g.nama_lengkap,k.nama_kelas,m.nama_mapel FROM pengajaran p JOIN guru g ON g.id=p.guru_id JOIN kelas k ON k.id=p.kelas_id JOIN mapel m ON m.id=p.mapel_id';$teachingParams=[];if(!$isAdmin){$teachingSql.=' WHERE p.guru_id=?';$teachingParams[]=$ownGuruId;}$teachingSql.=' ORDER BY g.nama_lengkap,m.nama_mapel,k.nama_kelas,p.tahun_ajaran DESC,p.semester';$stmt=$db->prepare($teachingSql);$stmt->execute($teachingParams);$teachings=$stmt->fetchAll();
$edit=null;if($isAdmin&&($editId=(int)($_GET['edit_id']??0))){$stmt=$db->prepare($select.$joins.' WHERE r.id=?');$stmt->execute([$editId]);$edit=$stmt->fetch()?:null;}
$success=$_SESSION['flash_success']??'';$error=$_SESSION['flash_error']??'';unset($_SESSION['flash_success'],$_SESSION['flash_error']);require_once __DIR__.'/header.php';require_once __DIR__.'/sidebar.php';
?>
<style>.rm-page .card{border-radius:16px}.rm-page .table-responsive table{min-width:760px}.rm-status{font-size:.76rem}@media(max-width:575.98px){.rm-page .card-body{padding:1rem}.rm-export{display:grid;grid-template-columns:1fr 1fr;width:100%;gap:.5rem}.rm-page .table-responsive table{font-size:.82rem}}</style>
<div id="page-content-wrapper" class="rm-page" style="background:#f5f7fb;min-width:0"><nav class="navbar top-navbar px-3 px-md-4 py-3"><div><h5 class="fw-bold mb-0"><i class="fa-solid fa-person-chalkboard text-primary me-2"></i><?= sanitize($pageTitle) ?></h5><small class="text-muted"><?= $isAdmin?'Catat, koreksi, dan validasi realisasi JP guru':'Lihat rekap JP berdasarkan bulan atau rentang tanggal' ?></small></div></nav><main class="container-fluid p-3 p-md-4" style="max-width:1450px;margin:auto">
<?php if($success):?><div class="alert alert-success"><?= sanitize($success) ?></div><?php endif;if($error):?><div class="alert alert-danger"><?= sanitize($error) ?></div><?php endif?>
<?php if($isAdmin):?><section class="card border-0 shadow-sm mb-4"><div class="card-body"><h6 class="fw-bold"><?= $edit?'Ubah':'Input' ?> Aktivitas Mengajar</h6><p class="small text-muted">Pilih guru terlebih dahulu. Mata pelajaran dan kelas akan mengikuti data pengajaran guru tersebut.</p><form method="post" class="row g-2 align-items-end"><input type="hidden" name="csrf_token" value="<?= sanitize($_SESSION['csrf_token']) ?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>"><div class="col-md-4 col-lg-3"><label class="form-label small">Guru</label><select id="rmTeacher" class="form-select" required><option value="">Pilih guru</option><?php foreach($teachers as $g):?><option value="<?= (int)$g['id'] ?>"><?= sanitize($g['nama_lengkap']) ?></option><?php endforeach?></select></div><div class="col-md-4 col-lg-3"><label class="form-label small">Mata Pelajaran</label><select id="rmSubject" class="form-select" required disabled><option value="">Pilih guru dahulu</option></select></div><div class="col-md-4 col-lg-3"><label class="form-label small">Kelas / Periode</label><select id="rmTeaching" name="pengajaran_id" class="form-select" required disabled><option value="">Pilih mapel dahulu</option></select></div><div class="col-sm-4 col-lg-2"><label class="form-label small">Tanggal</label><input type="date" name="tanggal" class="form-control" value="<?= sanitize($edit['tanggal']??date('Y-m-d')) ?>" required></div><div class="col-4 col-sm-3 col-lg-2"><label class="form-label small">Sesi</label><select name="jenis_sesi" class="form-select" required><?php foreach(['Pagi','Siang'] as $s):?><option <?= ($edit['jenis_sesi']??'Pagi')===$s?'selected':'' ?>><?= $s ?></option><?php endforeach?></select></div><div class="col-4 col-sm-2 col-lg-1"><label class="form-label small">Mulai</label><select name="jam_ke_mulai" id="rmStart" class="form-select"><?php for($i=1;$i<=6;$i++):?><option value="<?= $i ?>" <?= (int)($edit['jam_ke_mulai']??1)===$i?'selected':'' ?>><?= $i ?></option><?php endfor?></select></div><div class="col-4 col-sm-2 col-lg-1"><label class="form-label small">Selesai</label><select name="jam_ke_selesai" id="rmEnd" class="form-select"><?php for($i=1;$i<=6;$i++):?><option value="<?= $i ?>" <?= (int)($edit['jam_ke_selesai']??1)===$i?'selected':'' ?>><?= $i ?></option><?php endfor?></select></div><div class="col-sm-3 col-lg-1"><label class="form-label small">JP</label><input id="rmJp" class="form-control" readonly></div><div class="col-sm-3 col-lg-1"><button class="btn btn-primary w-100">Simpan</button></div></form></div></section><?php endif?>
<section class="card border-0 shadow-sm mb-4"><div class="card-body"><form method="get" class="row g-2 align-items-end"><?php if(!$isAdmin):?><div class="col-12 col-md"><label for="rmPeriodMode" class="form-label small">Periode</label><select id="rmPeriodMode" name="periode" class="form-select"><option value="bulan" <?= !$isRange?'selected':'' ?>>Bulanan</option><option value="rentang" <?= $isRange?'selected':'' ?>>Rentang Tanggal</option></select></div><?php endif?>
<div id="rmMonthField" class="col-12 col-sm-6 col-md <?= $isRange?'d-none':'' ?>"><label for="rmMonth" class="form-label small">Bulan</label><input id="rmMonth" type="month" name="bulan" class="form-control" value="<?= sanitize($month) ?>" <?= $isRange?'disabled':'' ?> required></div>
<?php if(!$isAdmin):?>
<div class="col-12 col-sm-6 col-md rm-range-field <?= !$isRange?'d-none':'' ?>"><label for="rmDateStart" class="form-label small">Tanggal Mulai</label><input id="rmDateStart" type="date" name="tanggal_mulai" class="form-control" value="<?= sanitize($isRange?$startInput:$periodStart) ?>" <?= !$isRange?'disabled':'' ?> required></div>
<div class="col-12 col-sm-6 col-md rm-range-field <?= !$isRange?'d-none':'' ?>"><label for="rmDateEnd" class="form-label small">Tanggal Selesai</label><input id="rmDateEnd" type="date" name="tanggal_selesai" class="form-control" value="<?= sanitize($isRange?$endInput:$periodEnd) ?>" <?= !$isRange?'disabled':'' ?> required></div>
<?php endif?><?php if($isAdmin):?><div class="col-6 col-md"><label class="form-label small">Guru</label><select name="guru_id" class="form-select"><option value="0">Semua Guru</option><?php foreach($teachers as $g):?><option value="<?= (int)$g['id'] ?>" <?= $teacherFilter===(int)$g['id']?'selected':'' ?>><?= sanitize($g['nama_lengkap']) ?></option><?php endforeach?></select></div><?php endif?><div class="col-6 col-md"><label class="form-label small">Kelas</label><select name="kelas_id" id="rmFilterClass" class="form-select"><option value="0">Semua Kelas</option><?php foreach($classes as $k):?><option value="<?= (int)$k['id'] ?>" <?= $classFilter===(int)$k['id']?'selected':'' ?>><?= sanitize($k['nama_kelas']) ?></option><?php endforeach?></select></div><div class="col-6 col-md"><label class="form-label small">Mapel</label><select name="mapel_id" id="rmFilterSubject" class="form-select"><option value="0">Semua Mapel</option><?php foreach($subjects as $m):?><option value="<?= (int)$m['id'] ?>" <?= $subjectFilter===(int)$m['id']?'selected':'' ?>><?= sanitize($m['nama_mapel']) ?></option><?php endforeach?></select></div><div class="col-md-auto"><button class="btn btn-primary w-100">Tampilkan</button></div></form></div></section>
<?php if($periodError):?><div class="alert alert-danger" role="alert"><?= sanitize($periodError) ?></div><?php else:?><p class="small text-muted mb-3">Periode ditampilkan: <strong><?= sanitize($periodLabel) ?></strong></p><?php endif?>
<div class="row g-3 mb-4"><?php foreach([[$totalLabel,rm_number($totalMonthly),'text-primary'],['Guru Aktif',$teacherCount,''],['Hari Tercatat',$dayCount,''],['Status',(!$isAdmin&&isset($validationByTeacher[$ownGuruId]))?'Divalidasi':'Berjalan',(!$isAdmin&&isset($validationByTeacher[$ownGuruId]))?'text-success':'text-warning']] as $c):?><div class="col-6 col-lg-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><small class="text-muted"><?= sanitize($c[0]) ?></small><h4 class="fw-bold <?= $c[2] ?>"><?= sanitize($c[1]) ?></h4></div></div></div><?php endforeach?></div>
<?php if(!$isAdmin && $isRange):?><section class="alert alert-info mb-4"><strong>Rekap hanya dapat dilihat</strong><div class="small">Validasi tetap dilakukan admin per bulan. Status Divalidasi berarti seluruh bulan yang memiliki catatan dalam rentang ini sudah divalidasi. Hubungi admin jika ada rincian yang perlu dikoreksi.</div></section><?php elseif(!$isAdmin):?><section class="alert <?= isset($validationByTeacher[$ownGuruId])?'alert-success':'alert-info' ?> mb-4"><?php if(isset($validationByTeacher[$ownGuruId])):?><strong><i class="fa-solid fa-circle-check me-1"></i>Rekap telah divalidasi admin</strong><div class="small">Divalidasi <?= date('d/m/Y H:i',strtotime($validationByTeacher[$ownGuruId]['divalidasi_pada'])) ?> dengan total <?= rm_number($validationByTeacher[$ownGuruId]['total_jp']) ?> JP.</div><?php else:?><strong><i class="fa-solid fa-circle-info me-1"></i>Rekap hanya dapat dilihat</strong><div class="small">Status bulan ini belum divalidasi admin. Hubungi admin jika terdapat rincian yang perlu dikoreksi.</div><?php endif?></section><?php endif?>
<section class="card border-0 shadow-sm mb-4"><div class="card-body"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><h6 class="fw-bold mb-0"><?= $isRange?'Rekap Periode per Guru':'Rekap Bulanan per Guru' ?></h6><small class="text-muted">Total seluruh mata pelajaran dan kelas dalam <?= $isRange?'rentang tanggal':'bulan' ?> terpilih. Filter kelas/mapel hanya berlaku pada rincian harian.</small></div><div class="rm-export"><?php if(!$periodError):?><a class="btn btn-sm btn-success" href="?<?= sanitize(http_build_query(array_merge($state,['format'=>'excel']))) ?>"><i class="fa-solid fa-file-excel me-1"></i>Excel</a> <a class="btn btn-sm btn-danger" href="?<?= sanitize(http_build_query(array_merge($state,['format'=>'pdf']))) ?>"><i class="fa-solid fa-file-pdf me-1"></i>PDF</a><?php else:?><span class="small text-muted">Perbaiki tanggal untuk mengekspor rekap.</span><?php endif?></div></div><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Guru</th><th class="text-end"><?= sanitize($totalLabel) ?></th></tr></thead><tbody><?php foreach($monthly as $r):$v=$validationByTeacher[(int)$r['guru_id']]??null;?><tr><td><strong><?= sanitize($r['nama_lengkap']) ?></strong><div class="mt-1"><span class="badge rm-status <?= $v?'bg-success':'bg-warning text-dark' ?>"><?= $v?'Divalidasi Admin':'Belum Divalidasi' ?></span></div><?php if($isAdmin):?><div class="mt-2"><?php if($v):?><form method="post" onsubmit="return confirm('Batalkan validasi agar data dapat dikoreksi? Setelah koreksi, admin perlu memvalidasi kembali.')"><input type="hidden" name="csrf_token" value="<?= sanitize($_SESSION['csrf_token']) ?>"><input type="hidden" name="action" value="revoke"><input type="hidden" name="guru_id" value="<?= (int)$r['guru_id'] ?>"><input type="hidden" name="periode_bulan" value="<?= sanitize($month) ?>"><button class="btn btn-sm btn-outline-warning">Buka Koreksi</button></form><?php else:?><form method="post" onsubmit="return confirm('Validasi seluruh rekap JP guru ini untuk bulan yang dipilih?')"><input type="hidden" name="csrf_token" value="<?= sanitize($_SESSION['csrf_token']) ?>"><input type="hidden" name="action" value="validate"><input type="hidden" name="guru_id" value="<?= (int)$r['guru_id'] ?>"><input type="hidden" name="periode_bulan" value="<?= sanitize($month) ?>"><button class="btn btn-sm btn-success"><i class="fa-solid fa-check me-1"></i>Validasi</button></form><?php endif?></div><?php endif?></td><td class="text-end fw-bold"><?= rm_number($r['total_jp']) ?> JP</td></tr><?php endforeach;if(!$monthly):?><tr><td colspan="2" class="text-center text-muted py-4">Belum ada data pada periode ini.</td></tr><?php endif?></tbody></table></div></div></section>
<section class="card border-0 shadow-sm mb-4"><div class="card-body"><h6 class="fw-bold">Rincian Harian</h6><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Hari/Tanggal</th><?php if($isAdmin):?><th>Guru</th><?php endif?><th>Mapel / Kelas</th><th>Sesi</th><th>Jam Ke</th><th class="text-end">JP</th><?php if($isAdmin):?><th>Aksi</th><?php endif?></tr></thead><tbody><?php foreach($details as $r):$locked=isset($validationByMonth[(int)$r['guru_id']][substr($r['tanggal'],0,7)]);?><tr><td><?= $days[date('l',strtotime($r['tanggal']))] ?><br><small><?= date('d/m/Y',strtotime($r['tanggal'])) ?></small></td><?php if($isAdmin):?><td><?= sanitize($r['nama_lengkap']) ?></td><?php endif?><td><?= sanitize($r['nama_mapel']) ?><br><small><?= sanitize($r['nama_kelas']) ?></small></td><td><span class="badge <?= $r['jenis_sesi']==='Pagi'?'bg-info text-dark':'bg-primary' ?>"><?= sanitize($r['jenis_sesi']) ?></span></td><td><?= (int)$r['jam_ke_mulai'] ?>–<?= (int)$r['jam_ke_selesai'] ?></td><td class="text-end fw-bold"><?= rm_number($r['jumlah_jp']) ?></td><?php if($isAdmin):?><td><?php if($locked):?><span class="text-success small"><i class="fa-solid fa-lock"></i> Terkunci</span><?php else:?><a class="btn btn-sm btn-outline-primary" href="?<?= sanitize(http_build_query(array_merge($state,['edit_id'=>$r['id']]))) ?>">Ubah</a> <form method="post" class="d-inline" onsubmit="return confirm('Hapus catatan JP ini?')"><input type="hidden" name="csrf_token" value="<?= sanitize($_SESSION['csrf_token']) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><button class="btn btn-sm btn-outline-danger">Hapus</button></form><?php endif?></td><?php endif?></tr><?php endforeach;if(!$details):?><tr><td colspan="<?= $isAdmin?7:6 ?>" class="text-center text-muted py-4">Belum ada aktivitas mengajar.</td></tr><?php endif?></tbody></table></div></div></section>
<section class="card border-0 shadow-sm"><div class="card-body"><h6 class="fw-bold">Monitoring JP per Hari</h6><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Tanggal</th><?php if($isAdmin):?><th>Guru</th><?php endif?><th class="text-end">JP</th></tr></thead><tbody><?php foreach($daily as $r):?><tr><td><?= $days[date('l',strtotime($r['tanggal']))].', '.date('d/m/Y',strtotime($r['tanggal'])) ?></td><?php if($isAdmin):?><td><?= sanitize($r['nama_lengkap']) ?></td><?php endif?><td class="text-end fw-bold"><?= rm_number($r['total_jp']) ?></td></tr><?php endforeach?></tbody></table></div></div></section>
</main></div><script>
(() => {
    const mode=document.getElementById('rmPeriodMode');
    if(!mode)return;
    const month=document.getElementById('rmMonth'),start=document.getElementById('rmDateStart'),end=document.getElementById('rmDateEnd');
    const dates=()=>{end.min=start.value;start.max=end.value;};
    const update=()=>{
        const range=mode.value==='rentang';
        document.getElementById('rmMonthField').classList.toggle('d-none',range);
        document.querySelectorAll('.rm-range-field').forEach(el=>el.classList.toggle('d-none',!range));
        month.disabled=range;start.disabled=end.disabled=!range;
        dates();
    };
    mode.addEventListener('change',update);start.addEventListener('change',dates);end.addEventListener('change',dates);update();
})();
</script><script>(()=>{const rows=<?= json_encode($teachings,JSON_UNESCAPED_UNICODE|JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT) ?>,option=(value,label)=>{const o=document.createElement('option');o.value=value;o.textContent=label;return o};const a=document.getElementById('rmStart'),b=document.getElementById('rmEnd'),j=document.getElementById('rmJp');if(a){const calc=()=>{if(+b.value<+a.value)b.value=a.value;j.value=(+b.value-+a.value+1)+' JP'};a.addEventListener('change',calc);b.addEventListener('change',calc);calc()}const filterClass=document.getElementById('rmFilterClass'),filterSubject=document.getElementById('rmFilterSubject');if(filterClass&&filterSubject&&<?= $isAdmin?'false':'true' ?>){const selectedSubject=<?= $subjectFilter ?>,loadFilterSubjects=()=>{filterSubject.replaceChildren(option(0,'Semua Mapel'));const seen=new Set;rows.filter(r=>!+filterClass.value||+r.kelas_id===+filterClass.value).forEach(r=>{if(!seen.has(+r.mapel_id)){seen.add(+r.mapel_id);filterSubject.append(option(r.mapel_id,r.nama_mapel))}});if([...filterSubject.options].some(o=>+o.value===selectedSubject))filterSubject.value=selectedSubject};filterClass.addEventListener('change',()=>{loadFilterSubjects();filterSubject.value='0'});loadFilterSubjects()}const teacher=document.getElementById('rmTeacher'),subject=document.getElementById('rmSubject'),teaching=document.getElementById('rmTeaching');if(!teacher)return;const selected=<?= (int)($edit['pengajaran_id']??0) ?>,current=rows.find(r=>+r.id===selected);const loadSubjects=()=>{subject.replaceChildren(option('','Pilih mata pelajaran'));teaching.replaceChildren(option('','Pilih mapel dahulu'));teaching.disabled=true;const seen=new Set;rows.filter(r=>+r.guru_id===+teacher.value).forEach(r=>{if(!seen.has(+r.mapel_id)){seen.add(+r.mapel_id);subject.append(option(r.mapel_id,r.nama_mapel))}});subject.disabled=!teacher.value;if(current&&+current.guru_id===+teacher.value)subject.value=current.mapel_id;loadClasses()};const loadClasses=()=>{teaching.replaceChildren(option('','Pilih kelas'));rows.filter(r=>+r.guru_id===+teacher.value&&+r.mapel_id===+subject.value).forEach(r=>teaching.append(option(r.id,r.nama_kelas+' · '+r.semester+' '+r.tahun_ajaran)));teaching.disabled=!subject.value;if(current&&+current.guru_id===+teacher.value&&+current.mapel_id===+subject.value)teaching.value=current.id};teacher.addEventListener('change',loadSubjects);subject.addEventListener('change',loadClasses);if(current){teacher.value=current.guru_id;loadSubjects()}})()</script><?php require_once __DIR__.'/footer.php'; ?>
